<?php $this->headScript()
        /*scriverà <script>src=......</script>*//*carico la libreria jquery*/
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
        /*scriverà <script>src=......</script>*/
	->appendFile($this->baseUrl('js/functions.js'))
        //mi permette di dire: da adesso in poi c è del codice jquery che devi aggiungere, questo finira quando definiro $this->headScript()->captureEnd()
	->captureStart() ?>


$(function() {
                    
        var UtenteLivello='<?php  
                                if($this->authInfo('Livello')== null){
            
                                    echo 'nonregistrato';
                                      
                                }
                                else{
                                    
                                    echo $this->authInfo('Livello');  
                                }
                            ?>';
       
        $('a#coupon1').on('click', function(){ Validation(UtenteLivello); })
    
});

<?php $this->headScript()->captureEnd() ?>


<div>
    <img src="<?php echo $this->baseUrl('css/images/coper.png');?>" alt="" width="920" height="343" border="0"> 
    <a href="#listTOP"><div id="button"></div></a>
</div>

<div id="listTOP">

    <?php
       //prendo tutte le categorie
       foreach ($this->CatTOP as $Cat){     

           $top=-1;
           $promozione=NULL;
            //prendo tutti i prodotti
            foreach ($this->PromozioniTOP as $promTOP){

                if(($promTOP->Categoria === $Cat->Nome) && ($promTOP->Coupon_emessi > $top)){

                     $promozione = $promTOP;
                     $top=$promTOP->Coupon_emessi;

                }    
            }

            if(!$promozione==NULL){
                
                echo '<div class="textarea">';
                echo '<h2>'.$promozione->Categoria.'</h2>';
                echo '<h4>'.$promozione->Nome.'</h4>';
                echo '<p class="Testo">'.$promozione->Descrizione_estesa.'</p>';
                echo '<h5 id="info">Azienda: ' . $promozione->Azienda . '</h5>' ;
                echo '<h5 id="info">Dove ritirarlo: ' . $promozione->Localizzazione. '</h5>' ;
                echo '<h5 id="info">Offerta: ' . $promozione->Offerta. '</h5>' ;
                echo '<h5 id="info">Scadenza: ' . $promozione->Fine_promozione . '</h5>'; 
                $Livello = $this->authInfo('Livello');
                    
                    if($Livello == null || $Livello == 'staff' || $Livello == 'admin'){

                         echo '<a  id="coupon1" ><img src=" '. $this->baseUrl('img/bottonc.png').' " alt="" width="150" height="50" /></a>';

                    }else{

                        echo '<a id="coupon1" href="'.$this->url(array('controller' => 'user',
                                                               'action'     => 'validatecoupon',
                                                               'prom' => $promozione->Id_promozione), 
                                                               'default',true ).'" ><img src=" '. $this->baseUrl('img/bottonc.png').' " alt="" width="150" height="50"/> </a>';
                    }
                
                echo '</div>';
                echo $this->productImg($promozione->Immagine, 'prom', array('id' => 'prodotto'));
                echo '<div class="clr"></div><hr>';
            }
        }
     ?>

   </div>
   <div class="clr"></div>
</div>
