<?php echo $this->doctype() ?>

<html>
    
    <head>
    <?= $this->headMeta(); ?>
    <?= $this->headTitle(); ?>
    <?= $this->headLink(); ?>
    </head>
    
    <body>
       
        <div class="logo" >
                 <h1>
                 <a href=" <?= $this->url(array('controller' => 'public',
                                                   'action'     => 'index', ), 
                                                   'default',true ); ?>"><small>L'offerta che vuoi, quando vuoi!</small>Coupon<span>Land</span></a>
                </h1>
        </div>
 
  <?php echo $this->registraForm ?>

        
        
        
        
    </body>
</html>