<div>
    
    <?php
          echo '<h1 class="Titolo">'. $this->IBRIDO .'</h1>'
    ?>
    
    <ul>
        <?php 
        
       
        foreach ($this->prom as $promozione) :?>
    
            <li class="prom">
		
                <div class="promlist">
                  <?php echo $this->productImg($promozione->Immagine, array('class' => 'imglist'), 'prom') ?>
                
                <div>	
                    
                    <?php 
                        echo'<h1 class="TestoLista"><a class="lista" href='. $this->url(array('controller' => 'public',
                                                                                 'action'     => 'promozione',
                                                                                 'Id_prom'  => $promozione->Id_promozione), 
                                                                                 'default', true) .'>' . $promozione->Nome . '<a></h1>' ;
                        echo '<p class="Desc_br">' . $promozione->Descrizione_breve . '</p>' ;
                        echo '<p>Azienda: ' . $promozione->Azienda . '</p>' ;
                        echo '<p>Scadenza: ' . $promozione->Fine_promozione . '</p>'; 
                     
                    ?>

                </div>

                </div>


               <hr class="separatore">
               
            </li>
            
	<?php endforeach ?>
        
    </ul>
	  
	  <!-- Paginazione -->	
         <!-- iNTRODUCE LA BARRA DI PAGINAZIONE -->
         
	  <?php if($this->prom instanceof Zend_Paginator) {
                        
                      echo $this->paginationControl($this->prom ,'Sliding','public/_paginator.phtml',array('chiamante'=>$this->chiamante));
	        } 
	  ?>

</div>