<div>
    
    <?php echo '<h1 class="Titolo">'. $this->IBRIDO .'</h1>' ?>
    
    <ul>
        <?php foreach ($this->prom as $promozione) :?>
    
            <li class="prom">
		
                <div class="promlist">
                  <?php echo $this->productImg($promozione->Immagine,  'prom' ,array('class' => 'imglist')) ?>
                </div>  
                
                <div class="info">
                    <?php 
                                echo '<h1 class="TestoLista">'. $promozione->Nome .'</h1>' ;
                                echo '<p class="Desc_br">' . $promozione->Descrizione_estesa . '</p>' ;
                                echo '<p>Azienda:' . $promozione->Azienda . '</p>' ;
                                echo '<p>Offerta: ' . $promozione->Offerta. '</p>' ;
                                echo '<p>Scadenza: ' . $promozione->Fine_promozione . '</p>'; 
                                echo '<input class="button" id="coupon" value="Coupon" onclick="ottienicoupon('.$this->authInfo('Livello').')">' ;
                            ?>
                        
                </div>
                
               
                <div style="clear:both;"></div>
                <hr class="separatore"> 
                
            </li>
            
	<?php endforeach ?>
        
    </ul>
	  
	  <!-- Paginazione -->	
         <!-- iNTRODUCE LA BARRA DI PAGINAZIONE -->
         
	  <?php if($this->prom instanceof Zend_Paginator) {
                        
                      echo $this->paginationControl($this->prom ,'Sliding','public/_paginator.phtml',array('chiamante'=>$this->chiamante));
	        } 
	  ?>

</div>