<div id="content">
    
        <?php 
        
        
        foreach ($this->prom as $promozione) :?>
    
		<div class="prod">
                    
                    <div class="image">
                      <?php echo $this->productImg($promozione->Immagine, array('class' => 'imagefrm')) ?>
                    </div>

                    <div class="info">		      
                      <?php echo'<h1><a href='. $this->url(array('controller' => 'public',
                                                                                     'action'     => 'promozione',
                                                                                     'Id_prom'  => $promozione->Id_promozione,
                                                                                     'chiamante' => 'promCat'), 
                                                                                     'default', true) .'>' . $promozione->Nome . '<a></h1>' ?>
                      <?php echo '<p class="Testo">' . $promozione->Descrizione_breve . '</p>' ?>
                      <?php echo '<p class="Sottotitolo">Azienda: ' . $promozione->Azienda . '</p>' ?>
                      <?php echo '<p>Scadenza: ' . $promozione->Fine_promozione . '</p>' ?>
                      
                    </div>
                
                </div>
    
	<?php endforeach ?>
	  
	  <!-- Paginazione -->	
         <!-- iNTRODUCE LA BARRA DI PAGINAZIONE -->
         
	  <?php if($this->prom instanceof Zend_Paginator) {
                        
                      echo $this->paginationControl($this->prom ,'Sliding','public/_paginator.phtml',array('chiamante'=>$this->chiamante));
	        } 
	  ?>

</div>