<div>
    <img src="/CouponLand/public/img/coper.png"  alt="" width="920" height="343" border="0"> 
    <a href="#listTOP"><div id="button"></div></a>
</div>

<div id="listTOP">

    <div class="textarea">
    <?php
       //prendo tutte le categorie
       foreach ($this->CatTOP as $Cat){     

           $top=0;
           $oggetto=NULL;
            //prendo tutti i prodotti
            foreach ($this->PromozioniTOP as $promTOP){

                if(($promTOP->Categoria === $Cat->Nome) && ($promTOP->Coupon_emessi > $top)){

                     $oggetto = $promTOP;
                     $top=$promTOP->Coupon_emessi;

                }    
            }

            if(!$oggetto==NULL){

                echo '<h2 >'.$oggetto->Categoria.'</h2>';
                echo '<h4>'.$oggetto->Nome.'</h4>';
                echo '<p class="Testo">'.$oggetto->Descrizione_breve.'</p>';
                echo '</div>';
                echo $this->productImg($oggetto->Immagine, array('id' => 'prodotto'), 'prom');


            }
        }
     ?>

   </div>
   <div class="clr"></div>
</div>
