<div>  
        <div>
            <img id="bodyimg"src="/CouponLand/public/img/coper.png"  alt="" width="920" height="343" border="0"> 
            <a href="#prima_categoria"><div id="button"></div></a>
        </div>
          
        <div class="textarea">
            <?php 
                
                $i =0;
                
                foreach ($this->PromozioniTOP as $promTOP) {
                    $i+=1;
                    if($i==1){
                       echo '<h2 id="prima_categoria">'. $promTOP->Categoria .'</h2>';  
                    }
                    else {
                       echo '<h2>'. $promTOP->Categoria .'</h2>';  
                    }
                    
                    echo '<p>'.$promTOP->Descrizione_breve.'</p>';
                    echo '<img scr='.$promTOP->Immagine.'</p>';
                    echo '<img id ="prodotto" src="/CouponLand/public/img/vaialprodotto" />';
                        
                }
            ?>
            
        </div>
    <div class="clr"></div>
</div>




