<?php $this->headScript()
        /*scriverà <script>src=......</script>*//*carico la libreria jquery*/
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
        /*scriverà <script>src=......</script>*/
	->appendFile($this->baseUrl('js/functions.js'))
        //mi permette di dire: da adesso in poi c è del codice jquery che devi aggiungere, questo finira quando definiro $this->headScript()->captureEnd()
	->captureStart() ?>


$(function() {
                    
        var UtenteLivello='<?php  
                                if($this->authInfo('Livello')== null){
            
                                    echo 'nonregistrato';
                                      
                                }
                                else{
                                    
                                    echo $this->authInfo('Livello');  
                                }
                            ?>';
       
        $('a#coupon').on('click', function(){ Validation(UtenteLivello); })
        
        
        

    $('img').on('click', function(e){
    
        var img = $(this).closest('div.promlist').find('img');
        
        $("#sfondo").css({"opacity" : "0.7"}).fadeIn("slow");

        $('div#ingrandita').html("<img width=500 height=400 src='"+img.attr("src")+"'>").fadeIn("slow");
        
    });
    
    $("#sfondo").on('click', function(){
    
      $("#sfondo").fadeOut("slow");
      $("#ingrandita").fadeOut("slow");
      
    });

    $("#ingrandita").on('click', function(){
    
      $("#sfondo").fadeOut("slow");
      $("#ingrandita").fadeOut("slow");
      
    });
    
 
    
});

<?php $this->headScript()->captureEnd() ?>

<div>
    
    <?php echo '<h1 class="Titolo">'. $this->IBRIDO .'</h1>' ?>
    
    <ul>
        <?php 
        
        
        
        if( ($this->prom == false || count($this->prom) == 0) && $this->chiamante == 'search'){
            
            echo '<h4>Parola cercata: '. $this->word.'</h4>';
            echo '<h4>Categoria selezionata: '. $this->cat .'</h4>';
            echo '<h4>Non ha prodotto nessun risultato</h4>';
            
            
        }
        else{
            if(count($this->prom) == 0){
            
            echo '<h4>Spiacenti. Non ci sono ancora promozioni '. $this->word.'</h4>';
            
        }
            
                echo '<div id="ingrandita"></div><div id="sfondo"></div>';
                foreach ($this->prom as $promozione) :?>
                    
                    <li class="prom">

                       <div class="promlist">
                         <?php echo $this->productImg($promozione->Immagine,  'prom' ,array('title' => 'click to zoom',
                                                                                            'class' => 'imglist')) ?>
                       </div>  

                       <div class="info">
                           <?php
                                echo '<h1 class="TestoLista">'. $promozione->Nome .'</h1>' ;
                                echo '<p class="Desc_br">' . $promozione->Descrizione_estesa . '</p>' ;
                                echo '<p>Azienda:' . $promozione->Azienda . '</p>' ;
                                echo '<p>Offerta: ' . $promozione->Offerta. '</p>' ;
                                echo '<p>Scadenza: ' . $promozione->Fine_promozione . '</p>'; 


                                $Livello = $this->authInfo('Livello');


                                if($Livello == null || $Livello == 'staff' || $Livello == 'admin'){

                                     echo '<a  id="coupon" >Coupon</a>';

                                }else{

                                    echo '<a id="coupon" href="'.$this->url(array('controller' => 'user',
                                                                           'action'     => 'validatecoupon',
                                                                           'prom' => $promozione->Id_promozione), 
                                                                           'default',true ).'" >Coupon</a>';
                                }


                            ?>
                        </div>
                       <div style="clear:both;"></div>
                       <hr class="separatore"> 
                    </li>
        <?php endforeach ?>
        <?php } ?>
        
    </ul>
	  
	  <!-- Paginazione -->	
         <!-- iNTRODUCE LA BARRA DI PAGINAZIONE -->
         
	  <?php if($this->prom instanceof Zend_Paginator) {
                        
                      echo $this->paginationControl($this->prom ,'Sliding','public/_paginator.phtml',array('chiamante' => $this->chiamante,
                                                                                                            'cat' => $this->cat,
                                                                                                            'word' => $this->word));
	        } 
	  ?>

</div>