    <div class="Titolo">
      <h1>Le nostre aziende</h1><br>
    </div>
<div id="ContentListAziende">
    <ul class="listaziende">
        
        <li class="prom" class="Sottotitolo">
            <h2>A-F</h2>
        </li>
        
        <?php 

            foreach ($this->listaziende as $azienda) {

                $ris = substr($azienda->Nome, 0 , 1);

                if($ris === 'A' || $ris === 'B' || $ris === 'C' || $ris === 'D' || $ris === 'E' || $ris === 'F'){

                    switch($this->chiamante){
                        
                        case 'nav':{
                            
                            echo '<li class="prom"><a href='. $this->url(array('controller' => 'public',
                                                               'action' => 'getpromozioni',
                                                               'IBRIDO'=> $azienda->Nome,
                                                               'chiamante' => 'promAz' ), 
                                                               'default', true) .'>'.
                                     $azienda->Nome.'</a></li>';
                            
                  
                            
                            break;
                        }
                        
                        case 'footer':{
                            
                            echo '<li class="prom"><a href='. $this->url(array('controller' => 'public',
                                                               'action' => 'azienda',
                                                               'id'=> $azienda->Id_azienda), 
                                                               'default', true) .'>'.
                                     $azienda->Nome.'</a></li>';
                            break;
                        }
                    
                    }
                    
                }
            }

        ?>
    </ul>
    
    <ul class="listaziende">   
        <li class="prom" class="Sottotitolo">
            <h2>G-O</h2>
        </li>
        
        <?php 
    
        foreach ($this->listaziende as $azienda) {

            $ris = substr($azienda->Nome, 0,1);
            
            if($ris === 'G' || $ris === 'H' || $ris === 'I' || $ris === 'L' || $ris === 'M' || $ris === 'N'|| $ris === 'O'){
                
                switch($this->chiamante){
                        
                        case 'nav':{
                            
                            echo '<li class="prom"><a href='. $this->url(array('controller' => 'public',
                                                               'action' => 'getpromozioni',
                                                               'IBRIDO'=> $azienda->Nome,
                                                               'chiamante' => 'promAZ' ), 
                                                               'default', true) .'>'.
                                     $azienda->Nome.'</a></li>';
                            
                  
                            
                            break;
                        }
                        
                        case 'footer':{
                            
                            echo '<li class="prom"><a href='. $this->url(array('controller' => 'public',
                                                               'action' => 'azienda',
                                                               'id'=> $azienda->Id_azienda), 
                                                               'default', true) .'>'.
                                     $azienda->Nome.'</a></li>';
                            break;
                        }
                    
                    }
            }
        }
    ?>
 
    </ul>

    <ul class="listaziende">
        
        <li class="prom" class="Sottotitolo">
            <h2>P-Z</h2>
        </li>
        
        <?php 
    
        foreach ($this->listaziende as $azienda) {

            $ris = substr($azienda->Nome, 0,1);
            
            if($ris === 'P' || $ris === 'Q' || $ris === 'R' || $ris === 'S' || $ris === 'T' || $ris === 'U'|| $ris === 'V' || $ris==='Z'){
                
               switch($this->chiamante){
                        
                        case 'nav':{
                            
                            echo '<li class="prom"><a href='. $this->url(array('controller' => 'public',
                                                               'action' => 'getpromozioni',
                                                               'IBRIDO'=> $azienda->Nome,
                                                               'chiamante' => 'promAz'), 
                                                               'default', true) .'>'.
                                     $azienda->Nome.'</a></li>';
                            
                  
                            
                            break;
                        }
                        
                        case 'footer':{
                            
                            echo '<li class="prom"><a href='. $this->url(array('controller' => 'public',
                                                               'action' => 'azienda',
                                                               'id'=> $azienda->Id_azienda), 
                                                               'default', true) .'>'.
                                     $azienda->Nome.'</a></li>';
                            break;
                        }
                    
                    }
            }
            
        }
    ?>
    
</ul>
</div>
 <div class="clr"></div>

