<div>
    
    <?php 
        if($this->promozione === null): 
    ?>
    
    <h2 class="Titolo">Elenco dei risultati:</h2>
    
    <p>Parola ricercata: <span><?= $this->word; ?></span></p>
    <p>Categoria ricercata: <span><?= $this->cat; ?></span></p>
    <p>Non sono stati trovati</p>
    <?php endif ?>
    
</div>


<?php 
        if($this->promozione != null): 
    ?>
        <?php foreach ($this->promozione as $promozione) :?>
    
            <ul>
            <li class="prom">
		
                <div class="promlist">
                  <?php echo $this->productImg($promozione->Immagine,  'prom' , array('class' => 'imglist')); ?>
                
                <div>	
                    
                    <?php 
                        echo'<h1 class="TestoLista"><a class="lista" href='. $this->url(array('controller' => 'public',
                                                                                 'action'     => 'promozione',
                                                                                 'Id_prom'  => $promozione->Id_promozione), 
                                                                                 'default', true) .'>' . $promozione->Nome . '<a></h1>' ;
                        echo '<p class="Desc_br">' . $promozione->Descrizione_estesa . '</p>' ;
                        echo '<p>Azienda: ' . $promozione->Azienda . '</p>' ;
                        echo '<p>Scadenza: ' . $promozione->Fine_promozione . '</p>'; 
                     
                    ?>

                </div>

                </div>


               <hr class="separatore">
               
            </li>
            </ul>
            
        <?php endforeach ?>
       <?php endif ?>



            


