<div id="Azienda">
                
    <h3>Azienda</h3>
    <a href=" <?= $this->url(array('controller' => 'public',
                                       'action'     => 'viewstatic',
                                       'staticPage' => 'chisiamo'), 
                                       'default',true ); ?>">Chi siamo</a>
    <br><br>
    <a href=" <?= $this->url(array('controller' => 'public',
                                       'action'     => 'viewstatic',
                                       'staticPage' => 'dovesiamo'), 
                                       'default',true ); ?>">Dove siamo</a>
    <br><br>
                
</div>
            
<div id="Ituoidiritti">
                
    <h3>I tuoi diritti</h3>
    
                
</div>

            
<div id="Seguici">
                
    <h3>Documentazione</h3>
    <a href=""></a>
    <a href=""></a>
                
</div>

