<?php echo $this->doctype() ?>
<html>
    
<head>
   
    <?= $this->headMeta(); ?>
    <?= $this->headLink(); ?>
    <?= $this->headTitle(); ?>
    
</head>

<body>
    
    <header class="header">
      
        <div class="header_resize">  
            
            <div class="logo">
                <h1>
                    <a href=" <?= $this->url(array('controller' => 'public',
                                                   'action'     => 'index', ), 
                                                   'default',true ); ?>">
                        
                        <small>L'offerta che vuoi, quando vuoi!</small>Coupon<span>Land</span>
                    </a>
                </h1>
            </div>

            <nav class="accedi_registati">
                <ul>
                  <li><a href="<?= $this->url(array('controller' => 'public',
                                                   'action'     => 'accedi',
                                                   'pagina'  => 'accesso'), 
                                                   'default',true ); ?>"><span> Accedi </span></a></li>
                  <li><label></label></li>
                  <li><a href="<?= $this->url(array('controller' => 'public',
                                                   'action'     => 'accedi',
                                                   'pagina'  => 'registrazione'), 
                                                   'default',true ); ?>"><span> Registrati </span></a></li>
                </ul>
            </nav>

            <nav class="menu">
                <?= $this->render('navpubblica.phtml') ?>
            </nav>
            
            <div class="search">
                <form id="form"  method="post" action="#">
                    <span><input name="barraricerca"  type="text" id="textfield" maxlength="50" placeholder="Che cosa stai cercando?" /></span>
                    <input class="button" type="submit"  value=" "/>
                </form>
                <div class="clr"></div>
            </div>
        
        </div>
        
        <div class="clr"></div>
      
    </header>
    
    
    <div class="body">
        
        <div class="body_resize">
          <?php echo $this->layout()->content; ?>
        </div>
      
    </div>
    
   
    
    <!--terminato header -->
    
    <footer class="footer">
        
        <div class="footer_resize">
            
            <div id="Azienda">
                <h3>Azienda</h3>
                <a href=" <?= $this->url(array('controller' => 'public',
                                                   'action'     => 'viewstatic',
                                                   'staticPage'=> 'chisiamo'), 
                                                   'default',true ); ?>">Chi siamo</a>
                <br><br>
                <a href=" <?= $this->url(array('controller' => 'public',
                                                   'action'     => 'viewstatic',
                                                   'staticPage' => 'dovesiamo'                ), 
                                                   'default',true ); ?>">Dove siamo</a>
                <br><br>
                <a>Aiutaci a migliorare</a>
            </div>
            
            <div id="Ituoidiritti">
                <h3>I tuoi diritti</h3>
                <a href="">FAQ</a>
            </div>
            
            <div id="Seguici">
                <h3>Seguici</h3>
                <a href=""></a>
                <a href=""></a>
            </div>
        </div>
        
        <div class="clr"></div>
        
    </footer>
    <!--terminato footer -->

</div>
    
</body>

