<?php echo $this->doctype() ?>
<html>
    
<head>
   
    <?= $this->headMeta(); ?>
    <?= $this->headLink(); ?>
    <?= $this->headTitle(); ?>
    <?= $this->headScript(); ?>
    
    <!-- acquisisce il livello dell'utente -->
    <?php $livello = $this->authInfo('Livello');?>
    <?php $user = $this->authInfo('User');?>
    <?php $user = $this->authInfo('Pass');?>

    
</head>

<body>
    
    <header class="header">
      
        <div class="header_resize">  
            
            <div class="logo">
                 <?php echo $this->authInfo('Livello') ?>
                <?php echo $this->authInfo('User') ?>
                 <?php echo $this->authInfo('Pass') ?>

                <h1>
                    <a href=" <?php
                                    if($livello == NULL){
                       
                                       echo $this->url(array('controller' => 'public',
                                                         'action'     => 'index' ), 
                                                         'default',true );
                         
                                    }
                                    else{

                                       echo $this->url(array('controller' => $livello,
                                                         'action'     => 'index' ), 
                                                         'default',true ); 
                                        
                                    }?>">
                        
                        <small>L'offerta che vuoi, quando vuoi!</small>Coupon<span>Land</span>
                    </a>
                </h1>
            </div>

            <nav class="accedi_registati">
                <?php  
               
                   if($livello == NULL){
                       
                        echo $this->render('navar.phtml');
                        
                    }
                    else{
                        
                        echo $this->render('naval.phtml');
                       
                    }
                    
                ?>
            </nav>
            
            <div class="search">
                
                <?php echo $this->ricercaForm ?>
                
            </div>


            <nav class="menu">
                <?php
                        
                    if ($livello == NULL || $livello == 'user'){

                        echo $this->render('topnav.phtml');

                    }
                    if($livello == 'admin'){
                        
                        echo $this->render('topnavadmin.phtml');
                        
                    }
                
                ?>
            </nav>
            
        </div>
        
        <div class="clr"></div>
      
    </header>
    <!--terminato header -->
    
    
    <div class="body">
        
        <div id="bodyresize"> 
           <?php echo $this->layout()->content; ?>
        </div>
        
     </div>
    
    
    
    <footer class="footer">
        
        <div class="footer_resize">
            
            <?php
                        
                if ($livello == NULL || $livello == 'user'){

                    echo $this->render('footer.phtml');

                }
                if($livello == 'admin'){

                    echo $this->render('footeradmin.phtml');

                }
                
            ?>
        </div>
        <div class="clr"></div>
    </footer>
    <!--terminato footer -->

</div>
    
</body>

