<?php echo $this->doctype() ?>
<html>
    
<head>
   
    <?= $this->headMeta(); ?>
    <?= $this->headLink(); ?>
    <?= $this->headTitle(); ?>
    
</head>

<body>
    
    <header class="header">
      
        <div class="header_resize">  
            
            <div class="logo">
                <h1>
                    <a href=" <?= $this->url(array('controller' => 'public',
                                                   'action'     => 'index', ), 
                                                   'default',true ); ?>">
                        
                        <small>L'offerta che vuoi, quando vuoi!</small>Coupon<span>Land</span>
                    </a>
                </h1>
            </div>

            <nav class="accedi_registati">
                <?= $this->render('navar.phtml') ?>
            </nav>
            
             <div class="search">
                
                <form id="form"  method="post" action="#">
                    <select title="Seleziona categoria per la ricerca" size="1" >
                    <span><input name="barraricerca"  type="text" id="textfield" maxlength="50" placeholder="Che cosa stai cercando?" /></span>
                     </select>
                    <input class="button" type="submit"  value="Cerca"/>
                </form>
             </div>

            <nav class="menu">
                <?= $this->render('navpubblica.phtml') ?>
            </nav>
        </div>
        
        <div class="clr"></div>
      
    </header>
    
    
    <div class="body">
        <div id="bodyresize"> 
           <?php echo $this->layout()->content; ?>
        </div>
     </div>
    
    <!--terminato header -->
    
    <footer class="footer">
        
        <div class="footer_resize">
            
            <div id="Azienda">
                
                <h3>Azienda</h3>
                <a href=" <?= $this->url(array('controller' => 'public',
                                                   'action'     => 'viewstatic',
                                                   'staticPage'=> 'chisiamo'), 
                                                   'default',true ); ?>">Chi siamo</a>
                <br><br>
                <a href=" <?= $this->url(array('controller' => 'public',
                                                   'action'     => 'viewstatic',
                                                   'staticPage' => 'dovesiamo'                ), 
                                                   'default',true ); ?>">Dove siamo</a>
                <br><br>
                <a>Aiutaci a migliorare</a>
                
            </div>
            
            <div id="Ituoidiritti">
                
                <h3>I tuoi diritti</h3>
                <a href=" <?= $this->url(array('controller' => 'public',
                                               'action' => 'faq'), 
                                               'default',true ); ?>"> FAQ </a>
                <br><br>
                <a href=" <?= $this->url(array('controller' => 'public',
                                               'action' => 'listaziende',
                                               'chiamante' => 'footer'), 
                                               'default',true ); ?>"> Info Aziende </a>
                
            </div>

            
            <div id="Seguici">
                
                <h3>Seguici</h3>
                <a href=""></a>
                <a href=""></a>
                
            </div>
            
        </div>
        
        <div class="clr"></div>
    </footer>
    <!--terminato footer -->

</div>
    
</body>

