<ul>
    <li><a href="<?= $this->url(array('controller' => 'user',
                                     'action'     => 'areariservata'), 
                                     'default',true ); ?>"><span> Area Riservata </span></a></li>
    <li><label></label></li>
    <li><a href="<?= $this->url(array('controller' => 'user',
                                     'action'     => 'logout'), 
                                     'default',true ); ?>"><span> Logout </span></a></li>
</ul>

