<ul>
    <li><a href="<?= $this->url(array('controller' => 'public',
                                     'action'     => 'accedi'), 
                                     'default',true ); ?>"><span> Accedi </span></a></li>
    <li><label></label></li>
    <li><a href="<?= $this->url(array('controller' => 'public',
                                     'action'     => 'registrati'), 
                                     'default',true ); ?>"><span> Registrati </span></a></li>
</ul>

