<ul id="Pricipale-a">
                    
    <li class="left"><a href="#" id="active" class="Principale-b">Home</a></li>

    <li id="MenuPrincipale" class="left"> <!--Lista delle Categorie -->
        <a href="#" class="Principale-b"> Categorie </a>

        <ul> <!-- Lista annidata: voci del sotto-menu -->
            <li><a href="#">Elettronica</a></li>
            <li><a href="#">Settore Alimentare</a></li>
            <li><a href="#">Abbigliamento</a></li>
            <li><a href="#">Trasporti</a></li>
            <li><a href="#">Soggiorni</a></li>
        </ul> <!-- Fine del sotto-menu -->

    </li> <!-- Chiudo il list-item -->

    <li class="left"><a href="#" class="Principale-b"> Aziende </a></li>
    <li class="left"><a href="mailto:CouponLand@libero.it" class="Principale-b" >Contattaci </a></li>
</ul>

