<ul id="Pricipale-a">
                    
    <li class="left"><a href="#" id="active" class="Principale-b">Home</a></li>

    <li id="MenuPrincipale" class="left"> <!--Lista delle Categorie -->
        <a href="#" class="Principale-b"> Categorie </a>

        <ul> <!-- Lista annidata: voci del sotto-menu -->
            
            <?php foreach ($this->CategorieTendina as $categoria) {
                
                        echo '<li><a href='. $this->url(array('controller' => 'public',
                                                              'action' => 'index'), 'default', true) .'>'.
                        $categoria->Nome.'</a></li>';
                        
                    }
            ?>

        </ul> <!-- Fine del sotto-menu -->

    </li> <!-- Chiudo il list-item -->

    <li class="left"><a href="#" class="Principale-b"> Aziende </a></li>
    <li class="left"><a href="mailto:CouponLand@libero.it" class="Principale-b" >Contattaci </a></li>
</ul>
