-- phpMyAdmin SQL Dump
-- version 4.6.5.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Creato il: Giu 16, 2017 alle 12:32
-- Versione del server: 10.1.21-MariaDB
-- Versione PHP: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `couponland`
--

-- --------------------------------------------------------

--
-- Struttura della tabella `aziende`
--

CREATE TABLE `aziende` (
  `Id_azienda` int(11) NOT NULL,
  `Nome` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `Ragione_sociale` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `Tipologia` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT 'Alimentari? elettronica?',
  `Logo_aziendale` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `Descrizione` varchar(3000) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `Localizzazione` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--
-- Dump dei dati per la tabella `aziende`
--

INSERT INTO `aziende` (`Id_azienda`, `Nome`, `Ragione_sociale`, `Tipologia`, `Logo_aziendale`, `Descrizione`, `Localizzazione`) VALUES
(5, 'auchan', 'spa', 'Alimentari', 'auchan.jpg', 'auchan Ã¨ una catena francese di supermercati e ipermercati, considerata una delle principali aziende operanti nel settore della grande distribuzione a livello internazionale.\r\n\r\nla catena Ã¨ parte del gruppo aziendale dell\'associazione famiglia mulliez, che possiede tra l\'altro anche l\'azienda kiabi.', 'via scataglini 6, an'),
(7, 'coop', 's.c.a.r.l.', 'Alimentari', 'coop.jpg', 'conad, acronimo di consorzio nazionale dettaglianti, Ã¨ una societÃ  cooperativa attiva nella grande distribuzione organizzata. con sede centrale a bologna, Ã¨ formata attualmente da 8 cooperative di dettaglianti e attraverso di esse opera in tutte le regioni italiane, inoltre ha un suo centro distributivo.\r\nil conad venne fondato a bologna il 13 maggio 1962 da 14 gruppi d\'acquisto dell\'italia centro-settentrionale, come struttura di coordinamento. intorno al 1973 si procedette alla definizione di un marchio, di una politica di vendita e promozione comuni, nonchÃ© alla razionalizzazione e alle fusioni dei gruppi di acquisto. nel 1988 iniziÃ² la modernizzazione della rete di vendita, e dal 1991 si procedette alla differenziazione delle insegne: conad per i supermercati, margherita - conad per le superette e pianeta - conad (ora ipermercato o superstore conad) per le grandi superfici.', 'via giordano bruno 42, an'),
(8, 'tuodÃ¬', 'spa', 'Alimentari', '-tuodi.jpg', 'tuodÃ¬ Ã¨ una catena italiana di punti vendita discount.\r\n\r\nquesto canale Ã¨ gestito tramite la societÃ  dico s.p.a., con sede legale a roma.\r\n\r\nfino ad aprile 2013 la societÃ , la cui sigla significava \"discount coop\", era controllata in modo congiunto da 7 delle 9 grandi cooperative del sistema coop: coop adriatica, coop estense, coop consumatori nordest, coop liguria, coop lombardia, novacoop e unicoop tirreno.\r\n\r\nattualmente Ã¨ di proprietÃ  del gruppo tuo.\r\n\r\ndico s.p.a. che ha attualmente oltre 400 negozi, ne contava nel 2011, 374 di cui 249 gestiti direttamente e 125 in franchising, con una presenza del marchio dico in 16 regioni italiane (non Ã¨ presente in basilicata, calabria, sardegna e sicilia).', 'via valenti 9, an'),
(9, 'h&m', 'spa', 'Abbigliamento', 'h&m.jpg', 'h & m hennes & mauritz ab, comunemente conosciuta come h&m (pronunciata ho och em), Ã¨ un\'azienda di abbigliamento svedese.\r\n\r\ndi proprietÃ  di h&m sono inoltre i marchi cheap monday, cos, monki, weekday e & other stories.\r\nfu fondata a vÃ¤sterÃ¥s in svezia nel 1947 da erling persson con il nome di hennes (\"per lei\" in svedese), dal momento che vendeva solo abiti femminili.\r\n\r\nnel 1968 persson acquisÃ¬ a stoccolma il negozio di attrezzatura e abbigliamento per caccia e pesca mauritz widforss, portando all\'inserimento di una collezione maschile nella gamma di prodotti e il cambio di nome in hennes & mauritz, abbreviato in h&m', 'corso giuseppe garibaldi 107, an'),
(10, 'ovs', 'spa', 'Abbigliamento', 'ovs.png', 'ovs (in precedenza oviesse) Ã¨ una societÃ  di abbigliamento per uomo, donna e bambino. il nome deriva da o.v.s., acronimo di \"organizzazione vendite speciali\".\r\n\r\nla societÃ  Ã¨ quotata presso la borsa valori di milano nell\'indice ftse italia mid cap.\r\nnel 1968 viene creata una catena di magazzini chiamata le \"coinette\", pensate per sopperire alla mancanza dei negozi coin in determinate zone cittadine o nei piccoli-medi centri.\r\n\r\nil primo negozio oviesse nasce a padova nel 1972 per poi arrivare ad avere negozi in buona parte d\'italia.', 'corso carlo alberto 26, an'),
(11, 'zara', 'spa', 'Abbigliamento', 'Zara.jpg', 'zara Ã¨ un marchio di abbigliamento e accessori con sede ad arteixo in galizia, nel nord della spagna, fondata nel 1975 da amancio ortega e sua moglie rosalÃ­a mera. Ã¨ il marchio principale del gruppo inditex.', 'corso giuseppe garibaldi 10, an'),
(12, 'conad', 'spa', 'Alimentari', 'conad.png', 'conad, acronimo di consorzio nazionale dettaglianti, Ã¨ una societÃ  cooperativa attiva nella grande distribuzione organizzata. con sede centrale a bologna, Ã¨ formata attualmente da 8 cooperative di dettaglianti e attraverso di esse opera in tutte le regioni italiane, inoltre ha un suo centro distributivo.\r\nil conad venne fondato a bologna il 13 maggio 1962 da 14 gruppi d\'acquisto dell\'italia centro-settentrionale, come struttura di coordinamento. intorno al 1973 si procedette alla definizione di un marchio, di una politica di vendita e promozione comuni, nonchÃ© alla razionalizzazione e alle fusioni dei gruppi di acquisto. nel 1988 iniziÃ² la modernizzazione della rete di vendita, e dal 1991 si procedette alla differenziazione delle insegne: conad per i supermercati, margherita - conad per le superette e pianeta - conad (ora ipermercato o superstore conad) per le grandi superfici.', 'via giordano bruno 22, an'),
(13, 'msc', 'spa', 'Viaggi', 'msc.jpg', 'la msc crociere Ã¨ una compagnia di navigazione, dedita al mercato delle crociere di livello standard (o di massa) e di livello premium-lusso (msc yacht club), con sede a ginevra e sedi operative a napoli, genova e venezia. la compagnia, a capitale interamente svizzero, impiega circa 15.500 dipendenti in tutto il mondo e ha uffici in 45 paesi.', 'via cesare battisti 9, ch'),
(14, 'costa crociere', 'spa', 'Viaggi', 'costa crociere.png', 'costa crociere Ã¨ una compagnia di navigazione italiana dedicata all\'attivitÃ  crocieristica. si tratta della flotta standard maggiore in europa.la costa crociere appartiene al gruppo carnival corporation & plc e controlla la tedesca aida kreuzfahrten; fino al 2014 il gruppo comprendeva anche la spagnola ibero cruceros, marchio nel frattempo dismesso.', 'via valenti 23, an'),
(15, 'ryanair', 'spa', 'Viaggi', 'rayanair.png', 'ryanair Ã¨ una compagnia aerea a basso costo irlandese con sede a dublino, la cui piÃ¹ importante base operativa Ã¨ l\'aeroporto di londra-stansted.\r\n\r\nÃ¨ la piÃ¹ grande compagnia aerea a basso costo d\'europa, operando piÃ¹ di 1 600 tratte e collegando 28 paesi europei e marocco. negli anni si Ã¨ evoluta in una compagnia aerea di profitto[1], mantenendo notevoli margini di guadagno. ryanair si Ã¨ caratterizzata per una rapida e continua espansione, resa possibile dalla deregolamentazione dell\'industria aerea europea del 1997. nel 2012 ha trasportato oltre 79 milioni di passeggeri, diventati 120 nel 2016, attestandosi cosÃ¬ al primo posto fra i vettori continentali[2]. oggi Ã¨ ritenuta essere la compagnia aerea piÃ¹ scelta dai viaggiatori a livello europeo, seguita dalla sua rivale easyjet, anch\'essa compagnia aerea a basso costo. i due hub sono dublino e londra stansted', 'via cesare battisti 41, ch'),
(16, 'unieuro', 'spa', 'Elettronica', 'unieuro.png', 'unieuro s.p.a. Ã¨ una delle principali catene italiane di elettronica di consumo ed elettrodomestici per numero di negozi (457 in tutta italia), con una quota di mercato del 18%[3].\r\n\r\nil gruppo, con sede a forlÃ¬ e polo logistico centrale a piacenza.\r\ndal 4 aprile 2017 unieuro s.p.a. Ã¨ quotata sul listino di borsa italiana, segmento star, a seguito del collocamento sul mercato del 35% del capitale sociale[6]. unieuro Ã¨ lâ€™unico retailer di elettronica di consumo quotato in italia.\r\n\r\noltre alla presenza fisica sul territorio nazionale, dove unieuro conta 171 negozi diretti, 9 punti vendita travel allâ€™interno dei principali scali aeroportuali italiani e 280 punti vendita affiliati, la societÃ  Ã¨ attiva anche nel canale business-to-business, focalizzato sulla vendita allâ€™ingrosso a clienti professionali, e nel canale online tramite la piattaforma unieuro.it, recentemente rafforzatosi con lâ€™acquisizione del 100% di monclick, uno dei maggiori operatori italiani dellâ€™e-commerce di elettronica di consumo.', 'via scataglini 7, an'),
(17, 'mediaworld', 'spa', 'Elettronica', 'mediaworld.jpg', 'media markt Ã¨ una catena di distribuzione tedesca specializzata nell\'elettronica e negli elettrodomestici di consumo. appartiene insieme a saturn al gruppo media saturn holding, una filiale del gruppo metro.\r\n\r\nla catena Ã¨ presente in austria, belgio, cina, germania, grecia, italia, paesi bassi, polonia, portogallo, russia, spagna, svezia, svizzera, turchia e ungheria.\r\n\r\nin tutti i paesi l\'insegna Ã¨ media markt, con l\'eccezione dell\'italia, dove viene usato media world.', 'via primo maggio 25, an'),
(18, 'euronics', 'spa', 'Elettronica', 'euronics.jpg', 'euronics Ã¨ un gruppo europeo di grande distribuzione, specializzato nell\'elettronica di consumo, con sede principale ad amsterdam. i membri di euronics sono tutti rivenditori indipendenti.\r\neuronics italia s.p.a. rappresenta il secondo socio per fatturato di euronics international, secondo solo alla germania. Ã¨ uno dei maggiori gruppi [1] nella distribuzione di elettrodomestici ed elettronica di consumo, nato nel settembre 1999 dall\'evoluzione del marchio get, costituito nel 1972, quando la domanda di elettrodomestici, televisori a colori e sistemi hi-fi diventava sempre piÃ¹ significativa.\r\n\r\nl\'organico complessivo ammonta ad oltre 5.000 collaboratori.', 'parco c cargo pier 23, an');

-- --------------------------------------------------------

--
-- Struttura della tabella `categoria`
--

CREATE TABLE `categoria` (
  `Id_categoria` int(11) NOT NULL,
  `Nome` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=COMPACT;

--
-- Dump dei dati per la tabella `categoria`
--

INSERT INTO `categoria` (`Id_categoria`, `Nome`) VALUES
(10, 'Alimentari'),
(11, 'Elettronica'),
(12, 'Abbigliamento'),
(13, 'Viaggi');

-- --------------------------------------------------------

--
-- Struttura della tabella `coupon_emessi`
--

CREATE TABLE `coupon_emessi` (
  `Id_coupon` int(11) NOT NULL,
  `User` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `Categoria` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `Id_promozione` int(11) NOT NULL,
  `Nome_promozione` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `Inizio_promozione` date NOT NULL,
  `Fine_promozione` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--
-- Dump dei dati per la tabella `coupon_emessi`
--

INSERT INTO `coupon_emessi` (`Id_coupon`, `User`, `Categoria`, `Id_promozione`, `Nome_promozione`, `Inizio_promozione`, `Fine_promozione`) VALUES
(122, 'giuseppe', '', 17, 'JORDAN SPORTSWEAR', '2017-06-14', '2018-06-14'),
(123, 'user', '', 17, 'JORDAN SPORTSWEAR', '2017-06-14', '2018-06-14'),
(124, 'user', '', 38, 'Olanda', '2017-06-14', '2018-03-10'),
(125, 'user', '', 43, 'Huawei P8 Lite', '2017-06-14', '2017-07-10');

-- --------------------------------------------------------

--
-- Struttura della tabella `faq`
--

CREATE TABLE `faq` (
  `Id_faq` int(11) NOT NULL,
  `Domanda` varchar(500) COLLATE utf8_bin NOT NULL,
  `Risposta` varchar(500) COLLATE utf8_bin NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--
-- Dump dei dati per la tabella `faq`
--

INSERT INTO `faq` (`Id_faq`, `Domanda`, `Risposta`) VALUES
(16, 'come va?', 'bener'),
(17, 'hg', 'hgj'),
(18, ',m.', 'klÃ²'),
(19, 'giÃ¹ sÃ¹?', 'di giÃ '),
(20, 'ciao combÃ ?', 'giÃ¹?'),
(21, 'Ã²Ã Ã¨', 'Ã Ã Ã Ã Ã¨Ã¨Ã²Ã²Ã²');

-- --------------------------------------------------------

--
-- Struttura della tabella `promozione`
--

CREATE TABLE `promozione` (
  `Id_promozione` int(11) NOT NULL,
  `Nome` varchar(25) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `Descrizione_estesa` varchar(3000) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `Immagine` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `Inizio_promozione` date NOT NULL,
  `Fine_promozione` date NOT NULL,
  `Offerta` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `Azienda` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `Localizzazione` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `Categoria` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `Coupon_emessi` int(11) NOT NULL COMMENT 'Quanti coupon sono stati emessi per questa promozione?'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--
-- Dump dei dati per la tabella `promozione`
--

INSERT INTO `promozione` (`Id_promozione`, `Nome`, `Descrizione_estesa`, `Immagine`, `Inizio_promozione`, `Fine_promozione`, `Offerta`, `Azienda`, `Localizzazione`, `Categoria`, `Coupon_emessi`) VALUES
(2, 'Cell Samsung', '                                Proin nonummy, lacus eget pulvinar lacinia, pede felis dignissim leo, vitae tristique magna lacus sit amet eros. Nullam ornare. Praesent odio ligula, dapibus sed, tincidunt eget, dictum ac, nibh. Nam quis lacus. Nunc eleifend molestie velit. Morbi lobortis quam eu velit. Donec euismod vestibulum massa. Donec non lectus. Aliquam commodo lacus sit amet nulla. Cras dignissim elit et augue. Nullam non diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In hac habitasse platea dictumst. Aenean vestibulum. Sed lobortis elit quis lectus. Nunc sed lacus at augue bibendum dapibus.', NULL, '0000-00-00', '2017-06-24', '', 'Nessuna azienda', '', 'Nessuna categoria', 12),
(3, 'LG TV OLED', '                                Proin nonummy, lacus eget pulvinar lacinia, pede felis dignissim leo, vitae tristique magna lacus sit amet eros. Nullam ornare. Praesent odio ligula, dapibus sed, tincidunt eget, dictum ac, nibh. Nam quis lacus. Nunc eleifend molestie velit. Morbi lobortis quam eu velit. Donec euismod vestibulum massa. Donec non lectus. Aliquam commodo lacus sit amet nulla. Cras dignissim elit et augue. Nullam non diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In hac habitasse platea dictumst. Aenean vestibulum. Sed lobortis elit quis lectus. Nunc sed lacus at augue bibendum dapibus.\n', 'lg_tv_oled.jpg', '0000-00-00', '2017-06-08', '50%', 'Nessuna azienda', '', 'Nessuna categoria', 19),
(4, 'Samsung Galaxy j1', '                                Proin nonummy, lacus eget pulvinar lacinia, pede felis dignissim leo, vitae tristique magna lacus sit amet eros. Nullam ornare. Praesent odio ligula, dapibus sed, tincidunt eget, dictum ac, nibh. Nam quis lacus. Nunc eleifend molestie velit. Morbi lobortis quam eu velit. Donec euismod vestibulum massa. Donec non lectus. Aliquam commodo lacus sit amet nulla. Cras dignissim elit et augue. Nullam non diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In hac habitasse platea dictumst. Aenean vestibulum. Sed lobortis elit quis lectus. Nunc sed lacus at augue bibendum dapibus.\n', 'galaxy_j7.jpg', '0000-00-00', '2017-06-30', '70%', 'Unieruro', '', 'Nessuna categoria', 10),
(5, 'SMARTPHONE HUAWEI MATE9', '                                Proin nonummy, lacus eget pulvinar lacinia, pede felis dignissim leo, vitae tristique magna lacus sit amet eros. Nullam ornare. Praesent odio ligula, dapibus sed, tincidunt eget, dictum ac, nibh. Nam quis lacus. Nunc eleifend molestie velit. Morbi lobortis quam eu velit. Donec euismod vestibulum massa. Donec non lectus. Aliquam commodo lacus sit amet nulla. Cras dignissim elit et augue. Nullam non diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In hac habitasse platea dictumst. Aenean vestibulum. Sed lobortis elit quis lectus. Nunc sed lacus at augue bibendum dapibus.\n', 'Huawei_mate9.jpg', '0000-00-00', '2017-07-21', '50%', 'Unieuro', '', 'Nessuna categoria', 11),
(6, 'CANON POWERSHOT G7 X', '                                Proin nonummy, lacus eget pulvinar lacinia, pede felis dignissim leo, vitae tristique magna lacus sit amet eros. Nullam ornare. Praesent odio ligula, dapibus sed, tincidunt eget, dictum ac, nibh. Nam quis lacus. Nunc eleifend molestie velit. Morbi lobortis quam eu velit. Donec euismod vestibulum massa. Donec non lectus. Aliquam commodo lacus sit amet nulla. Cras dignissim elit et augue. Nullam non diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In hac habitasse platea dictumst. Aenean vestibulum. Sed lobortis elit quis lectus. Nunc sed lacus at augue bibendum dapibus.\n', 'Canon_Power_Shot_G7_X.jpg', '0000-00-00', '2017-06-22', '3X2', 'Nessuna azienda', '', 'Nessuna categoria', 25),
(7, 'LG G6', '                                Proin nonummy, lacus eget pulvinar lacinia, pede felis dignissim leo, vitae tristique magna lacus sit amet eros. Nullam ornare. Praesent odio ligula, dapibus sed, tincidunt eget, dictum ac, nibh. Nam quis lacus. Nunc eleifend molestie velit. Morbi lobortis quam eu velit. Donec euismod vestibulum massa. Donec non lectus. Aliquam commodo lacus sit amet nulla. Cras dignissim elit et augue. Nullam non diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In hac habitasse platea dictumst. Aenean vestibulum. Sed lobortis elit quis lectus. Nunc sed lacus at augue bibendum dapibus.\n', 'Lg_g6.jpg', '0000-00-00', '2016-05-30', '40%', 'Nessuna azienda', '', 'Nessuna categoria', 7),
(8, 'Caciocavallo pugliese Dop', '                                Proin nonummy, lacus eget pulvinar lacinia, pede felis dignissim leo, vitae tristique magna lacus sit amet eros. Nullam ornare. Praesent odio ligula, dapibus sed, tincidunt eget, dictum ac, nibh. Nam quis lacus. Nunc eleifend molestie velit. Morbi lobortis quam eu velit. Donec euismod vestibulum massa. Donec non lectus. Aliquam commodo lacus sit amet nulla. Cras dignissim elit et augue. Nullam non diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In hac habitasse platea dictumst. Aenean vestibulum. Sed lobortis elit quis lectus. Nunc sed lacus at augue bibendum dapibus.\n', 'caciocavalloDOP.jpg', '0000-00-00', '2017-06-15', '50%', 'auchan', '', 'Nessuna categoria', 30),
(14, 'HURLEY DRI-FIT JOGGER', 'FIT COMODO ED ELEGANTE.\r\nI pantaloni 73,5 cm Hurley Dri-FIT Jogger - Uomo, caratterizzati da un look essenziale, sono realizzati in tessuto traspirante ed elastico per il massimo comfort per tutti i giorni.\r\n\r\nVANTAGGI\r\nTecnologia Dri-FIT per pelle asciutta e comfort\r\nTessuto elasticizzato e tassello al cavallo per movimenti naturali\r\nCintura elastica in vita con laccetti e polsini elastici per un fit sicuro.\r\n\r\nDETTAGLI PRODOTTO\r\nTasche multiple per organizzare i tuoi oggetti\r\nTessuto: Corpo: Dri-FIT 63% nylon/33% poliestere/4% spandex. Tasca: 100% poliestere.\r\nLavabile in lavatrice\r\nProdotto importato\r\nDI\' LA TUA', 'HURLEY DRI-FIT JOGGER.jpg', '2017-06-14', '2018-05-12', '3x2', 'h&m', '', 'Abbigliamento', 2),
(15, 'HURLEY PHANTOM', 'COMFORT CHE SI MUOVE CON TE\r\nGli shorts da surf 45,5 cm Hurley Phantom Block Party Hyperweave Speed - Uomo sono realizzati in morbido tessuto elasticizzato e caratterizzati da un taglio ad alte prestazioni per il massimo comfort e una mobilitÃ  ideale sulla tavola e in spiaggia.\r\n\r\nVANTAGGI\r\nFit moderno ad alte prestazioni e cavallo da 45,5 cm per una libertÃ  di movimento naturale\r\nCintura con tecnologia Hyperweave per un fit sicuro\r\nTessuto Phantom riciclato con il 60% di elasticitÃ \r\nBordo Dolphin per una maggiore copertura\r\n\r\nDETTAGLI PRODOTTO\r\nTaschina con zip per proteggere i tuoi oggetti\r\nTessuto: 86% poliestere riciclato/14% spandex\r\nLavabile in lavatrice\r\nProdotto importato', 'HURLEY PHANTOM BLOCK PARTY HYPERWEAVE SPEED.jpg', '2017-06-14', '2018-06-13', '3x2', 'zara', '', 'Abbigliamento', 1),
(16, 'HURLEY PHANTOM', 'LIBERTÃ€ DI MOVIMENTO\r\nGli shorts da surf 45,5 cm Hurley Phantom Hyperweave Motion Stripe - Uomo sono resistenti ed elasticizzati per movimenti naturali in acqua e sulla spiaggia.\r\n\r\nVANTAGGI\r\nInserti laterali ultraelasticizzati e orli smerlati per la massima libertÃ  di movimento\r\nCintura Hyperweave per un fit adattabile\r\nTessuto Phantom riciclato con il 60% di elasticitÃ \r\nTasca a basso profilo per riporre i piccoli oggetti\r\n\r\nDETTAGLI PRODOTTO\r\nChiusura con patta finta\r\nTessuto: 86% poliestere riciclato/14% spandex\r\nLavabile in lavatrice\r\nProdotto importato', 'HURLEY PHANTOM HYPERWEAVE MOTION STRIPE.jpg', '2017-06-14', '2018-06-14', '30%', 'ovs', '', 'Abbigliamento', 2),
(17, 'JORDAN SPORTSWEAR', 'LEGGEREZZA E COPERTURA\r\nLa giacca Jordan Sportswear Wings Windbreaker - Uomo Ã¨ caratterizzata da un design elegante e dotata di cappuccio a collo alto regolabile per una protezione leggera dal vento.\r\n\r\nVANTAGGI\r\nCappuccio a collo alto regolabile foderato in mesh per una copertura traspirante.\r\nPolsini e bordo elastici per un fit confortevole e sicuro\r\nManiche con taglio raglan per una libertÃ  di movimento naturale.\r\nInserto di ventilazione sul retro per ottimizzare la traspirabilitÃ .\r\nTasche laterali con zip.\r\n\r\nDETTAGLI PRODOTTO\r\nTessuto: 100% poliestere\r\nLavabile in lavatrice\r\nProdotto importato', 'JORDAN SPORTSWEAR WINGS WINDBREAKER.jpg', '2015-06-16', '2018-06-14', '30%', 'h&m', '', 'Abbigliamento', 7),
(18, 'NIKE AIR MAX 97', 'ESCLUSIVO LOOK RETRÃ’\r\nLa scarpa Nike Air Max 97 OG QS - Uomo rende omaggio alle linee fluide e alla rivoluzionaria ammortizzazione dell\'originale.\r\n\r\nVANTAGGI\r\nTomaia in pelle e tessuto per un comfort e una resistenza eccezionali\r\nDettagli rifrangenti per una visibilitÃ  ottimale in condizioni di scarsa luminositÃ \r\nAmmortizzazione Max Air a tutta lunghezza per un comfort leggero\r\nResistente suola in gomma per una trazione ideale su piÃ¹ superfici\r\n\r\nORIGINI DELLA SCARPA NIKE AIR MAX\r\nAlla fine degli anni \'70 la rivoluzionaria unitÃ  Air-Sole fece il suo ingresso nella linea Nike Footwear. Il 1987 segna il debutto della Nike Air Max 1, primo modello con unitÃ  Air visibile nel tallone, che mostra agli estimatori le caratteristiche della nuova tecnologia, oltre a offrire tutti i benefici tipici di Air-Sole. Da allora, la nuova Nike Air Max Ã¨ diventata un modello di grande successo sia tra gli atleti che tra i collezionisti. La scarpa Ã¨ stata prodotta in esclusive combinazioni di colore offrendo leggerezza e ammortizzazione straordinarie.', 'NIKE AIR MAX 97 OG QS.jpg', '2017-06-14', '2018-06-14', '40%', 'ovs', '', 'Abbigliamento', 3),
(19, 'NIKE AIR ZOOM PEGASUS 34', 'La piÃ¹ recente scarpa da running Nike Air Zoom Pegasus 34 - Uomo Ã¨ realizzata in tessuto Flymesh per traspirabilitÃ  e leggerezza eccezionali ed Ã¨ dotata di un\'ammortizzazione reattiva che assicura il massimo comfort chilometro dopo chilometro.\r\nIl tessuto Flymesh senza cuciture, leggero e traspirante, contribuisce a ridurre il surriscaldamento e promuove un comfort duraturo.\r\n\r\nI cavi Dynamic Flywire avvolgono l\'arco del piede per un supporto confortevole e una calzata sicura e aderente.\r\nLa schiuma Cushlon premium e l\'unitÃ  Zoom Air su tallone e avampiede contribuiscono a creare una sensazione elastica e reattiva sotto al piede.\r\n\r\nParziale rivestimento interno in mesh per un maggiore comfort\r\nControtacco rigido per una calzata stabile\r\nCrash rail in gomma ai lati della suola per transizioni fluide\r\nGomma in rilievo per assorbire gli impatti e una trazione ideale\r\nPiccoli tagli nella suola per una flessibilitÃ  ideale\r\nPeso: 295 g (misura da uomo 44)\r\nDifferenziale: 10 mm', 'NIKE AIR ZOOM PEGASUS 34.jpg', '2017-06-14', '2018-06-14', '10%', 'zara', '', 'Abbigliamento', 0),
(20, 'NIKE SB X NUMBERS', 'La polo Nike SB x Numbers Dry - Uomo prosegue la collaborazione con Numbers, nuovo marchio dedicato allo skate, lanciato da due professionisti leggendari, Eric Koston e Guy Mariano. Caratterizzata da un classico look stile college e tecnologia traspirante, questa polo in edizione limitata Ã¨ pensata per le tue sessioni sulla tavola e adatta in qualsiasi altra occasione.\r\n\r\nLa tecnologia Dri-FIT favorisce la traspirabilitÃ  per assicurare pelle asciutta e comfort accelerando l\'evaporazione del sudore.\r\n\r\nGli occhielli ricamati nel giromanica e lo scollo traspirante assicurano la giusta circolazione dell\'aria dove serve di piÃ¹ assicurando la massima freschezza quando la sessione entra nel vivo.\r\n\r\nTessuto: Dri-FIT 58% cotone/42% poliestere\r\nLavabile in lavatrice\r\nProdotto importato', 'NIKE SB X NUMBERS.jpg', '2017-06-14', '2018-06-14', '20%', 'h&m', '', 'Abbigliamento', 0),
(21, 'NIKECOURT POWER', 'COMFORT IN CAMPO\r\nIl pagliaccetto da tennis Nike Power - Donna Ã¨ realizzato in tessuto traspirante ed elasticizzato per contribuire a mantenere la pelle asciutta e assicurare comfort e libertÃ  di movimento in campo.\r\n\r\nVANTAGGI\r\nTessuto Nike Flex (shorts) per un\'elasticitÃ  che segue i movimenti del corpo e una libertÃ  di movimento ottimale\r\nTessuto Nike Power (maglia) per compression fit e il giusto supporto\r\nTecnologia Dri-FIT per pelle asciutta e comfort\r\nDesign senza maniche per una libertÃ  di movimento ottimale\r\nZip posteriore termosaldata per indossare agevolmente il capo\r\n\r\nDETTAGLI PRODOTTO\r\nTessuto: Parte superiore del corpo: 88% poliestere riciclato/12% spandex. Parte inferiore del corpo: 86% poliestere/14% spandex.\r\nLavabile in lavatrice\r\nProdotto importato', 'NIKECOURT POWER.jpg', '2017-06-14', '2018-06-14', '30%', 'zara', '', 'Abbigliamento', 0),
(22, 'Chardonnay', 'UVE\r\nChardonnay 100%.\r\n\r\nAREA DI PRODUZIONE\r\nNel cuore della provincia di Chieti, tra il Parco Nazionale della Maiella e il mare Adriatico.\r\n\r\nTERRENI\r\nCollinari, con altitudine media di 230 metri s.l.m., prevalentemente argillosi-calcarei.\r\n\r\nEPOCA DI COMMERCIALIZZAZIONE\r\nMese di dicembre dello stesso anno in cui Ã¨ avvenuta la vendemmia.\r\n\r\nVINIFICAZIONE E AFFINAMENTO\r\nBreve macerazione a freddo del pigiato, pigiatura soffice e fermentazione a temperatura controllata in serbatoi di acciaio inox.\r\n\r\nCARATTERISTICHE ORGANOLETTICHE\r\nColore bianco con note verdastre, profumo fruttato, intenso ed elegante; nel gusto equilibrato, con retrogusto che ricorda la mela verde.\r\n\r\nABBINAMENTI GASTRONOMICI\r\nEccellente con tutta la cucina a base di pesce, si accompagna bene anche con pietanze delicate a base di carne. Ottimo con antipasti e come aperitivo.\r\n\r\nGRADAZIONE ALCOLICA\r\n12% alc./vol.\r\n\r\nCHIUSURE\r\nDisponibile con tappo tradizionale raso bocca.', 'chardonnay.jpg', '2017-06-14', '2017-08-14', '3x2', 'auchan', '', 'Alimentari', 1),
(23, 'montepulciano', 'AREA DI PRODUZIONE\r\n\r\nNel cuore della provincia di Chieti, tra il Parco Nazionale della Maiella e il mare Adriatico.\r\n\r\nTERRENI\r\nCollinari, con altitudine media di 230 metri s.l.m., prevalentemente argillosi-calcarei.\r\n\r\nEPOCA DI COMMERCIALIZZAZIONE\r\nViene stabilita dallâ€™enologo in relazione alle caratteristiche ottimali del prodotto. In ogni caso non prima del mese di aprile/maggio dellâ€™anno successivo a quello di vinificazione.\r\n\r\nVINIFICAZIONE E AFFINAMENTO\r\nMacerazione delle bucce a temperatura controllata in vinificatori di acciaio inox.\r\n\r\nCARATTERISTICHE ORGANOLETTICHE\r\nColore rosso rubino, profumo vinoso e intenso, sapore morbido e giusto equilibrio tannico.\r\n\r\nABBINAMENTI GASTRONOMICI\r\nCompagno ideale della tipica cucina italiana, si accompagna egregiamente ai primi con sughi di carne e alle grigliate di carni sia rosse che bianche. Ottimo con formaggi vari di media stagionatura.\r\n\r\nGRADAZIONE ALCOLICA\r\n13% alc./vol.\r\n\r\nCHIUSURE\r\nDisponibile con tappo tradizionale raso bocca.', 'montepulciano.png', '2017-06-14', '2017-08-14', '3x2', 'conad', '', 'Alimentari', 0),
(24, 'olio boschino', 'Olio Extra Vergine di Oliva BOSCHINO Â® 100% Italiano, categotia fruttato monocultivar ogliarola salentina â€“ non filtrato, ottenuto da olive piÃ¹ verdi, colore verde smeraldo intenso, ha note fruttate di media intensitÃ , dalle nette connotazioni erbacee. Al palato si apre elegante e morbido, ha buona fluiditÃ  e corpo, gusto che rimanda al carciofo e al cardo, con note amare e piccanti spiccate ma in buon equilibrio. Prodotto non filtrato.\r\nÃˆ un olio Extravergine di oliva di alta qualitÃ  ottenuto da Uliveti Secolari coltivati a Bosco di varietÃ  Ogliarola Salentina, siti a pochi km dalle coste del mar Ionio nei pressi di Porto Cesareo (Il Cuore della Macchia Mediterranea).\r\nLâ€™Olio Boschino Ã¨ ottenuto attraverso Spremitura a Freddo nel frantoio oleario aziendale lo stesso giorno della raccolta, nel rispetto delle tradizioni secolari della produzione olearia Salentina.\r\nLa sua aciditÃ  risulta bassissima e ciÃ² lo rende un olio di altissimo pregio e di grande eccellenza.\r\nVerde smeraldo intenso, ha note fruttate di media intensitÃ , dalle nette connotazioni erbacee. Al palato si apre elegante e moribdo, ha buona fluiditÃ  e corpo, gusto che rimanda al carciofo e al cardo, con note amare e piccanti spiccate ma in buon equilibrio.', 'olio boschino.jpg', '2017-06-14', '2017-08-14', '3x2', 'coop', '', 'Alimentari', 0),
(25, 'olio Schirzini', 'Olio Extra Vergine dâ€™Oliva SANTA LUCIA 100% Italiano, categoria fruttato delicato, di colore giallo verdognolo, con riflessi dorati ottenuto mediante spremitura di olive al giusto grado di maturazione, selezionate e colte direttamente dallâ€™albero di varietÃ  nostrane pugliesi del Salento (Multivarietale): Ogliarola, Cellina di NardÃ², Leccino, Nociara e Frantoio. Di carattere delicato ed equilibrato, al palato si sprigionano piacevoli note appena amare e piccanti, mentre lâ€™olfatto richiama sentori erbacei delicati e mandorlati.\r\nMolitura con Spremitura a Freddo nel frantoio oleario aziendale.\r\nIl prodotto ha unâ€™aciditÃ  bassissima, pertanto secondo la piÃ¹ diffusa dottrina letteraria lâ€™olio extravergine di oliva Ã¨ di per sÃ¨ un alimento di categoria superiore ricco di vitamine A, D, E, K e acidi grassi insaturi Essenziali, protettori naturali contro lâ€™invecchiamento e le malattie cardiovascolari.\r\nIntegrata a basso impatto ambientale, rappresenta un sistema di produzione agricola che utilizza tutti i metodi agronomici e di difesa dalle avverstÃ  per ridurre al minimo lâ€™uso delle sostanze chimiche (prodotti fitosanitari e fertilizzanti), ma anche dellâ€™acqua e dellâ€™energia. Lo scopo della produzione integrata Ã¨ quindi di ottenere produzioni di qualitÃ  nel rispetto dellâ€™ambiente e della salute dellâ€™uomo.', 'Schirzini.jpg', '2017-06-14', '2017-08-14', '3x2', 'coop', '', 'Alimentari', 0),
(26, 'salame milano', 'PESO: kg 3,4.\r\n\r\nLUNGHEZZA: cm 52.\r\n\r\nCALIBRO: cm 11.\r\n\r\nMACINATURA: fine, a grana di riso.\r\n\r\nQUALITÃ€: carni pregiate di puro suino nazionale.\r\n\r\nSPEZIE E AROMI: un velo di pepe nero spezzato.\r\n\r\nSAPORE: dolce, classico del salame Milano. La fetta Ã¨ compatta dal colore uniforme grazie alla lenta e sapiente stagionatura.\r\n\r\nBUDELLO: artificiale.\r\n\r\nASPETTO ESTERNO: spazzolato.\r\n\r\nTAGLIO: a macchina, obliquo. Fetta sottile. I fondi piatti garantiscono unâ€™alta resa in affettatura.\r\n\r\nGARANZIE: senza glutine e derivati del latte.', 'Salame Milano.jpg', '2017-06-14', '2017-08-14', '20%', 'tuodÃ¬', '', 'Alimentari', 0),
(27, 'salame villani', 'PESO: g 330.\r\n\r\nLUNGHEZZA: cm 18.\r\n\r\nCALIBRO: cm 6.\r\n\r\nMACINATURA: medio-fine.\r\n\r\nQUALITÃ€: carni di puro suino selezionate, per un prodotto unico, di grande successo, riconosciuto e richiesto dai migliori buongustai italiani ed esteri.\r\n\r\nSPEZIE E AROMI: vino bianco secco e pepe bianco macinato finemente e pepe nero intero.\r\n\r\nSAPORE: deciso, appetitosamente piccante. Unâ€™emozione per palati sofisticati.\r\n\r\nBUDELLO: naturale.\r\n\r\nASPETTO ESTERNO: forma schiacciata assai particolare.\r\n\r\nTAGLIO: a mano, leggermente obliquo, mm 2.\r\n\r\nGARANZIE: senza glutine.', 'salame villani.jpg', '2017-06-14', '2017-09-14', '3x2', 'auchan', '', 'Alimentari', 0),
(28, 'San Daniele', 'Viene prodotto esclusivamente in Friuli Venezia Giulia nel territorio collinare dellâ€™omonimo comune in provincia di Udine, nellâ€™estremo nord est dâ€™Italia. Riconoscibile per la caratteristica forma a chitarra, la presenza dello zampino e il marchio del Consorzio, il San Daniele Ã¨ fatto solo con carne di suini nati e allevati in Italia e sale marino. Ãˆ un alimento naturale privo di additivi o conservanti. Lâ€™alto valore nutrizionale e la facile digeribilitÃ  lo rendono indicato per qualsiasi tipo di dieta.\r\nIl saper fare il prosciutto si tramanda da secoli a San Daniele del Friuli. La cura per ogni particolare, i gesti propri del mestiere insieme al clima del luogo consentono il ripetersi della tradizione secolare della stagionatura della coscia del maiale.\r\n\r\nPoichÃ© Ã¨ vietata qualsiasi forma di congelamento delle carni, le cosce fresche devono raggiungere rapidamente San Daniele del Friuli, per essere lavorate ricreando il ritmo naturale delle stagioni, con lâ€™utilizzo del sale marino, senza lâ€™aggiunta di additivi o conservanti.\r\n\r\nA San Daniele la stagionatura deve durare almeno 13 mesi.', 'San Daniele.jpg', '2017-06-14', '2018-06-14', '30%', 'conad', '', 'Alimentari', 0),
(29, 'Trebbiano d\'Abruzzo', 'UVE\r\nTrebbiano dâ€™Abruzzo 100%\r\n\r\nZONA DI PRODUZIONE\r\nNel cuore della provincia di Chieti, tra il Parco Nazionale della Maiella e il mare Adriatico.\r\n\r\nTERRENI\r\nCollinari, con altitudine media di 230 metri s.l.m., prevalentemente argillosi-calcarei.\r\n\r\nEPOCA DI COMMERCIALIZZAZIONE\r\nGennaio/Febbraio dellâ€™anno successivo a quello di vendemmia.\r\n\r\nVINIFICAZIONE E AFFINAMENTO\r\nBreve macerazione a freddo del pigiato, pigiatura soffice e fermentazione a temperatura controllata in serbatoi di acciaio inox.\r\n\r\nCARATTERISTICHE ORGANOLETTICHE\r\nColore giallo paglierino con gradevoli profumi fruttati di frutta esotica, che si uniscono a delicate note floreali. Di buona struttura, morbido, sapido e persistente.\r\n\r\nABBINAMENTI GASTRONOMICI\r\nIdeale con tutta la cucina a base di pesce, primi piatti delicati, carni bianche, formaggi freschi e a pasta filata. Ottimo come aperitivo.\r\n\r\nGRADAZIONE ALCOLICA\r\n12% alc./vol.\r\n\r\nCHIUSURE\r\nDisponibile sia con tappo tradizionale raso bocca\r\nche con tappo a vite BVS.', 'trebbianodabruzzo.png', '2017-06-14', '2018-06-14', '20%', 'tuodÃ¬', '', 'Alimentari', 0),
(30, 'Alberobello', 'Facciamo un salto nella Terra dei Trulli? Queste bizzarre costruzioni famose in tutto il mondo vi aspettano, cosÃ¬ coma la splendida Valle d\'Itria, dove alloggerete presso un\'elegante masseria 4 stelle, molto vicino alla bellissima cittadina di Alberobello! Il prezzo Ã¨ davvero competitivo, soprattutto considerando il livello della struttura e le tante date disponibili a luglio, agosto e settembre! Continuate a leggere, qui sotto potrete prenotare il vostro lussuoso soggiorno!\r\nVi suggeriamo il Victor Country Hotel (4/5 TripAdvisor), posto all\'interno di una masseria del XIX secolo, nel cuore della Valle d\'Itria, ad Alberobello. Le camere, elegantemente arredate, sono dotare di aria condizionata, minibar, TV, bagno privato Parcheggio e connessione Wifi sono gratuiti.\r\nLa localitÃ  pugliese Ã¨ famosa in tutto il mondo per i trulli, caratteristiche costruzioni in pietra locale tutte di forma e dimensioni diverse. Questa localitÃ  Ã¨ anche un ottimo punto di partenza per visitare la Valle d\'Itria, territorio ricco di boschi, ulivi e viti e di numerosi borghi caratteristici, che vale la pena esplorare. Senza dimenticare che all\'utile si puÃ² unire il dilettevole, ovvero la deliziosa cucina pugliese che avrete modo di provare direttamente in loco.', 'Alberobello.jpg', '2017-06-14', '2018-06-14', '20%', 'costa crociere', '', 'Viaggi', 0),
(31, 'Alicante', 'Vi portiamo ad Alicante, il frizzante capoluogo della Costa Blanca! Non sarÃ  famosa come Madrid o Barcellona, ma vi assicuriamo che Ã¨ un posto magnifico, una cittÃ  balneare piena di vita che vi aspetta col suo clima mite, i suoi locali, il cibo e tante attrazioni da scoprire. Vi suggeriamo un soggiorno di 2 notti pernottando in una struttura centrale a pochi minuti dalla spiaggia a un prezzo davvero niente male. Volo e soggiorno si prenotano separatamente, fatelo adesso!\r\nWonderfull Garden& House in CEntre. WIFI (4,5/5 Airbnb) situato a pochi metri dal centro storico, vanta un bel giardino e un terrazzo privato di 40 mq.\r\nLa caliente cittÃ  situata nel sud-est della Spagna vi conquisterÃ  con il suo incantevole Castillo de Santa BÃ¡rbara, la Cattedrale di San Nicola, il Municipio e la Chiesa di Santa Maria, il Parco de El Palmeral e il Tossal de Manises.', 'Alicante.jpg', '2017-06-14', '2018-04-13', '10%', 'msc', '', 'Viaggi', 0),
(32, 'Cile', 'Approfittate degli ottimi voli per il Cile che abbiamo trovato con partenza da molti aeroporti italiani con destinazione Santiago del Cile, la capitale a partire da soli 406â‚¬ per un viaggio di andata e ritorno, con tasse e bagagli inclusi. Un prezzo incredibile, considerando le normali tariffe per raggiungere il Paese sudamericano nel quale vi consigliamo di immergervi nella sua natura straordinaria, ammirando varietÃ  incredibile di paesaggi tanto diversi fra loro! Trovate tutti i dettagli dell\'offerta qui di seguito.\r\nAl vostro arrivo a Santiago del Cile, vi proponiamo di soggiornare presso l\'Hotel Foresta, struttura ben valutata su TripAdvisor con 4 punti su 5 sulla base di oltre 110 recensioni e vincitrice dei premi Travellers\' Choice. Situato a soli 200 metri dal Museo di Belle Arti, offre camere dotate di servizi privati, connessione Wi-Fi gratuita e TV via cavo.', 'cile.jpg', '2017-06-14', '2018-06-12', '30%', 'ryanair', '', 'Viaggi', 0),
(33, 'Croazia', 'Siete alla ricerca di un viaggio al mare nei mesi estivi senza spendere una fortuna? Ecco allora l\'offerta che fa per voi, per visitare una delle piÃ¹ belle isole della Croazia ad un ottimo prezzo! Vi proponiamo di raggiungere la rinomata localitÃ  balneare di Pag, in Dalmazia, caratterizzata da mare cristallino, natura selvaggia e divertimenti sfrenati! Abbiamo creato per voi un pacchetto che comprende soggiorno presso un\'ottima struttura a pochi passi dal mare ed ottimi voli low cost! Volo e struttura vanno prenotati separatamente, approfittatene.\r\nApartments Mira (Booking 8,3/10), distante a pochissima distanza dal mare, offre appartamenti con una terrazza, un\'area salotto, una cucina completamente accessoriata con frigorifero e utensili, e un bagno privato con doccia e asciugacapelli.\r\nPer esplorare l\'isola e le sue innumerevoli spiagge, vi consigliamo di prenotare un\'auto a noleggio, fatelo sul nostro motore di ricerca auto, dove troverete ottimi prezzi e auto per tutti i budget. Assicuratevi di presentare una carta di credito (no debito o prepagata) intestata al guidatore principale al momento del ritiro dell\'auto perchÃ¨ senza di essa potrebbe esservi negata la consegna.', 'croazia.jpg', '2017-06-14', '2018-06-14', '10%', 'msc', '', 'Viaggi', 0),
(34, 'Edimburgo', 'Vi proponiamo Flat to rent on Holyrood park (Airbnb 5/5) tranquillo ed accogliente appartamento a a poca distanza dal centro di Edimburgo.\r\nPERIODO DI VIAGGIO: settembre 2017\r\n\r\nPERIODO PER PRENOTARE: al piÃ¹ presto, le tariffe potrebbero aumentare!\r\nEcco le 10 cose che vi consigliamo di fare assolutamente in questa splendida cittÃ :\r\n\r\nSalire al Castello di Edimburgo sulla collina di Castle Hill, con una splendida vista\r\nVisitare il Palazzo di Holyrood House, residenza scozzese della regina Elisabetta e luogo di curiositÃ  e segreti\r\nEsplorare la cittÃ  antica seguendo il Royal Mile, miglio reale dove troverete tanti bellissimi edifici, negozi e tipici pub\r\nProvare lo Scottish tablet, che non Ã¨ uno strano aggeggio tecnologico ma un buonissimo dolce fatto di zucchero, latte condensato e burro cristallizzati e aromatizzati con vaniglia o whisky.\r\nFare shopping nelle boutiques di Princes Street\r\nScoprire tutto quello che dovete sapere sul whisky con un tour allo Scotch Whisky Heritage Centre\r\nVisitare il museo degli scrittori, proprio nella cittÃ  che l\'UNESCO ha definito CittÃ  della letteratura\r\nMangiare come dei veri scozzesi provando l\'Haggis, un gustosissimo piatto ricco di spezie e interiora di pecora con contorno di rape e patate\r\nAndare a curiosare al Tartan Weaving Mill, centro commerciale dedicato ai kilt, ai souvenir e ai prodotti tipici\r\nBere una tazza di tÃ¨ alla scozzese, rigorosamente nero, senza zucchero e macchiato con un po\' di latte', 'Edimburgo.jpg', '2017-06-14', '2018-05-14', '40%', 'ryanair', '', 'Viaggi', 0),
(35, 'Formentera', 'A grandissima richiesta, vi proponiamo una vacanza di una settimana nella favolosa isola di Formentera in piena estate! Saprete tutti che, essendo una localitÃ  abbastanza \"alla moda\", i prezzi proposti non sono quelli a cui siete abituati; ma rimangono super competitivi tenuto conto di meta e periodo. Abbiamo optato per una bellissima casa privata vicino al mare e con vista, completa di vari i comfort! Il nostro pacchetto include anche delle eccellenti tariffe aeree per Ibiza, con partenza da diversi aeroporti e il traghetto da Ibiza a Formentera. Di seguito ci sono tutti i dettagli dell\'offerta, volo e soggiorno vanno prenotati separatamente, approfittatene!\r\nPerfect location & great views (4,5/5 Airbnb), bellissimo appartamento luminoso, arredato in stile moderno e con con terrazza, in una posizione privilegiata a poche decine di metri dal mare, dispone di cucina, TV e servizi privati con biancheria e asciugacapelli.\r\nPiccola e tranquilla, Formentera Ã¨ il posto ideale in cui rilassarsi e godersi la bellezza del suo mare e delle spiagge, come Playa de ses Illetes e Playa de Llevant. Come Minorca, anche Formentera Ã¨ stata dichiarata Riserva Naturale e Patrimonio dell\'UmanitÃ  dall\'Unesco.', 'Formentera.jpg', '2017-06-14', '2018-06-12', '20%', 'msc', '', 'Viaggi', 0),
(36, 'Grecia', 'Lefkada,una delle piÃ¹ belle isole della Grecia, dove troverete spiagge sabbiose meravigliose, un entroterra selvaggio, taverne tipiche che servono piatti squisiti e gente cordiale! I pacchetti comprendono volo diretto e 7 notti in un appartamento situato a poca distanza dal mare, nel mese di settembre, ottimo periodo per visitare l\'isola. Non aspettate che i prezzi salgano, prenotate adesso la vostra fantastica vacanza sotto il sole della Grecia!\r\nConosciuta anche con il nome di Leuca, Lefkada o Santa Maura (secondo l\'antica denominazione veneziana) Ã¨ bagnata dalle acque del Mar Ionio, vicino alle isole di Cefalonia e Zacinto ed Ã¨ l\'unica isola greca raggiungibile anche via terra perchÃ© collegata con un ponte mobile alla Grecia continentale. Se amate il mare vi consigliamo di visitare le spiagge di Porto Katsiki ed Egremmi (quest\'ultima al momento raggiungibile solo via mare), che, fidatevi di noi, sono tra le piÃ¹ belle di tutta la Grecia!', 'Grecia.jpg', '2017-06-14', '2018-05-10', '10%', 'costa crociere', '', 'Viaggi', 0),
(37, 'Marocco', 'Pronti per una vacanza in stile le mille e una notte a base di hammam e massaggi nell\'affascinante Marrakech Ecco dei pacchetti volo diretto+soggiorno presso un bellissimo riad 5 stelle situato nella medina della cittÃ  marocchina, suo cuore pulsante. Si parte da diversi aeroporti a prezzi davvero niente male, considerando il valore e i servizi della struttura; date un\'occhiata di seguito, siamo sicuri che ne rimarrete entusiasti e non vi lascerete sfuggire questa bella offerta. Volo e soggiorno si prenotano insieme. \r\ni pacchetti il Marocco prevedono voli diretti e soggiorno in camera matrimoniale al Riad & Spa Ksar Saad a 5* (4/5 TripAdvisor e Certificato di Eccellenza). Situato nella medina, a 10 minuti a piedi da Piazza Jamaa el Fna, vanta un hammam e sauna, offre la colazione e dispone di camere con arredi classici, bagno privato con set di cortesia e WiFi.\r\nLa rinomata piazza Jemaa el-Fna offre quello che Ã¨ forse il piÃ¹ grande spettacolo all\'aperto del mondo: giocolieri e cantastorie si contendono lo spazio con incantatori di serpenti, maghi e acrobati! Un\'altra delle attrazioni piÃ¹ incredibili Ã¨ il giardino di Majorelle, situato fuori dalla cittÃ  vecchia. Il giardino raccoglie tantissime varietÃ  di cactus e piante grasse di ogni genere. Immancabile anche il Souk, dove potrete divertirvi a percorrere i numerosi vicoli dove potrete trovare splendide lampade, stoffe e tanti diversi souvenir. Infine vi consigliamo di fare un salto al Marrakesh Henna Art Cafe, dove oltre a provare qualche piatto tipico, potrete farvi tatuare con l\'hennÃ¨.', 'Marocco.jpg', '2017-06-14', '2018-02-13', '20%', 'msc', '', 'Viaggi', 0),
(38, 'Olanda', 'Ahoy Pirati, vi proponiamo un fantastico pacchetto Fly & Drive per visitare l\'Olanda nel richiestissimo mese di agosto! La terra dei tulipani e dei mulini a vento, con i suoi bellissimi colori vi aspetta! Abbiamo selezionato per voi degli ottimi voli per raggiungere Amsterdam ed Eindhoven a un prezzo niente male considerando il periodo, a cui abbiamo abbinato il noleggio dell\'auto per l\'intero soggiorno. Vi ricordiamo che volo e auto vanno prenotati separatamente, approfittatene ora prima che i prezzi salgano!\r\nUna volta atterrati ad Eindhoven o Amsterdam, vi consigliamo di noleggiare un\'auto direttamente in aeroporto, che poi riconsegnerete prima di imbarcarvi sul volo di ritorno. Potete prenotarla sul nostro motore di ricerca auto. Una sola raccomandazione: assicuratevi di presentare una carta di credito (no debito) intestata al guidatore principale dell\'auto che sarÃ  necessaria per ill ritiro del mezzo, perchÃ© senza quella potrebbe esservi negata la consegna.', 'Olanda.jpg', '2017-06-14', '2018-03-10', '10%', 'ryanair', '', 'Viaggi', 1),
(39, 'Parigi', 'vogliamo proporvi un bel weekend a Parigi, per scoprire questa magnifica cittÃ  unica al mondo, da visitare almeno una volta nella vita! Abbiamo selezionato un ottimo hotel situato in buona posizione e i voli piÃ¹ economici, in partenza da molte cittÃ  italiane durante l\'estate! Qui di seguito troverete tutti i dettagli dell\'offerta e vi ricordiamo che volo e hotel vanno prenotati separatamente.\r\nVi consigliamo l\'Hotel Des Buttes Chaumont (4/5 TripAdvisor), situato a meno di 50 metri dalla fermata della metro Jaures, da dove si raggiunge Montmartre in meno di 10 minuti, vanta camere con bagno privato, prodotti da bagno, asciugacapelli, TV e Wi-Fi.\r\nLa capitale francese non ha invece bisogno di presentazioni. A Parigi c\'Ã¨ tantissimo da vedere e vi consigliamo una romantica passeggiata al calar del sole, ammirando la Tour Eiffel illuminata o lungo la Senna, con un favoloso panorama. Oppure potrete scegliere una delle oltre 300 lingue del mondo per dirvi ti amo, vi basterÃ  scegliere quella giusta sul Mur des Je T\'Aime a Montmartre.', 'Parigi.jpg', '2017-06-14', '2017-09-14', '20%', 'ryanair', '', 'Viaggi', 1),
(40, 'ASUS ZenPad', 'ASUS ZenPad 3 8.0 Ã¨ un tablet premium da 7.9 pollici con luminoso display 2K (risoluzione 2048 x 1536) e audio cinematografico per un intrattenimento davvero coinvolgente. Il suo elegante design con una finitura metallica spazzolata e dettagliati cerchi concentrici, fornisce un livello sublime di eleganza e bellezza, mentre il velocissimo processore hexa-core, e i 4GB di RAM forniscono potenti prestazioni per ogni utilizzo. Assieme alla nuovissima Interfaccia ZenUI 3.0, ZenPad 3 8.0 offre unâ€™esperienza incredibile di utilizzo.\r\nASUS ZenPad 3 8.0 ha un design moderno e contemporaneo che colpisce. Il suo corpo in alluminio pesa solo 320g, ed ha una cover posteriore con fantasia simil pelle gradevole al tatto.\r\nSUS ZenPad 3 8.0 ha una finitura metallica spazzolata e una trama finemente dettagliata a cerchi concentrici che riflette il giusto equilibrio tra bellezza e forza. La sua perfetta superficie viene ottenuta grazie ad un finissimo processo di sabbiatura, prima di essere lucidato per la finitura anodizzata.', 'ASUS ZenPad 3 8.0 (Z581KL).jpg', '2017-06-14', '2017-08-14', '20%', 'euronics', '', 'Elettronica', 0),
(41, 'Dell Vostro', 'Notebook da 15\" (355,6 mm) ideale per i professionisti. Dotato di un ampio schermo, tastierino numerico e caratteristiche essenziali per la sicurezza.\r\nDisponibile con Windows 10 Pro\r\n\r\nI nuovi ed eleganti notebook Vostro offrono il giusto equilibrio tra prestazioni e sicurezza.\r\nAumenta la produttivitÃ : i processori IntelÂ® Coreâ„¢ di ultima generazione offrono tutta la potenza necessaria per aumentare la produttivitÃ  in ufficio o a casa. Ãˆ possibile scegliere la scheda grafica dedicata AMD integrata con 2 GB di vRAM DDR3L per prestazioni superiori.\r\n\r\nMaggiore capacitÃ  di memoria: con fino a 2 SoDIMM e fino a 8 GB di memoria DDR4, chi sfrutta il multitasking puÃ² tenere piÃ¹ applicazioni aperte contemporaneamente e passare da una all\'altra senza problemi di latenza.', 'Dell Vostro 15 3568.png', '2017-06-14', '2017-08-05', '30%', 'mediaworld', '', 'Elettronica', 0),
(42, 'Honor 6C', 'Honor 6C Ã¨ un smartphone Android di buon livello, fortemente votato all\'imaging, in grado di soddisfare anche l\'utente piÃ¹ esigente. Dispone di un grande display Touchscreen da 5 pollici con una risoluzione di 1280x720 pixel non particolarmente elevata. Sul versante delle funzionalitÃ  a questo Honor 6C non manca davvero nulla. A cominciare dal modulo LTE 4G che permette un trasferimento dati e una navigazione in internet eccellente, passando per la connettivitÃ  Wi-fi e il GPS. \r\nQuesto Honor 6C Ã¨ un prodotto con pochi competitor per ciÃ² che riguarda la multimedialitÃ  grazie alla fotocamera da ben 13 megapixel che permette al Honor 6C di scattare foto di alta qualitÃ  con una risoluzione di 4208x3120 pixel e di registrare video in fullHD alla risoluzione di 1920x1080 pixel. Lo spessore di 7.6mm Ã¨ veramente contenuto e rende questo Honor 6C ancora piÃ¹ spettacolare. \r\nprocessore e Ram per unâ€™esperienza fluida; buone foto per la categoria; lettore impronte digitali veloce e preciso; autonomia batteria ottima; software proprietario.', 'Honor 6C.jpg', '2017-06-14', '2017-07-18', '30%', 'unieuro', '', 'Elettronica', 0),
(43, 'Huawei P8 Lite', 'Huawei P8 Lite Ã¨ un smartphone Android completo, che non ha molto da invidare ai dispositivi piÃ¹ avanzati. Dispone di un grande display Touchscreen da 5 pollici con una discreta risoluzione di 1280x720 pixel. Sul versante delle funzionalitÃ  a questo Huawei P8 Lite non manca davvero nulla. A cominciare dal modulo LTE 4G che permette un trasferimento dati e una navigazione in internet eccellente, passando per la connettivitÃ  Wi-fi e il GPS. \r\nQuesto Huawei P8 Lite Ã¨ un prodotto con pochi competitor per ciÃ² che riguarda la multimedialitÃ  grazie alla fotocamera da ben 13 megapixel che permette di scattare foto fantastiche con una risoluzione di 4160x3120 pixel e di registrare video in fullHD alla risoluzione di 1920x1080 pixel. Lo spessore di 7.7mm Ã¨ veramente contenuto e rende questo Huawei P8 Lite ancora piÃ¹ spettacolare. \r\nHuawei P8 Lite Ã¨ piÃ¹ compatto di P8, ma Ã¨ leggermente piÃ¹ spesso, rimanendo comunque uno dei prodotti piÃ¹ sottili per questa tipologia di smartphone. Tutto il metallo Ã¨ stato sostituito dalla plastica, mantenendo comunque una buona sensazione al tatto, anche grazie alla finitura simil-metallica del retro. Non Ã¨ uno smartphone scivoloso e si arriva bene a premere i tasti laterali, del volume e di accensione.', NULL, '2017-06-14', '2017-07-10', '40%', 'euronics', '', 'Elettronica', 2),
(44, 'Oukitel U7 Plus', '5,5 pollici HD Android 6.0 4G smartphone quad-core a 1,3 GHz 2 GB di RAM 16 GB ROM scanner di impronte digitali GPS Dual SIM 13 MP - Grigio\r\n\r\nSul lato sinistro troviamo i due pulsanti per il bilanciere del volume, su quello destro il tasto di Standby, sul bordo inferiore microUSB, speaker e microfono, sul lato superiore il jack per le cuffie, sulla facciata anteriore altoparlante, fotocamera e sensore di prossimitÃ  sul bordo superiore e tre tasti capacitivi sul quello inferiore. Infine, sul retro del telefono troviamo fotocamera, flash LED e sensore per le impronte digitali.Tutto il corpo Ã¨ in plastica: anche il guscio posteriore, che a prima vista potrebbe sembrare in alluminio, in realtÃ  Ã¨ in plastica con una piacevole satinatura al tatto che, insieme al maggiore spessore, offre una migliore presa del dispositivo. Anche senza nessuna custodia di fatto non scivola e si impugna davvero bene, anche semplicemente bloccandolo tra due dita ai bordi.Non ci sono cassetti per SIM e microSD: per accedere a questi slot Ã¨ necessario sollevare il guscio posteriore aiutandosi con il piccolo incavo posizionato nellâ€™angolo in basso a destra del dispositivo (vedi foto). Lâ€™operazione, necessaria non solo per inserire le schede ma anche per rimuovere la pellicola che protegge i contatti della batteria, puÃ² risultare leggermente difficoltosa in quanto la scocca Ã¨ bloccata su piÃ¹ punti attraverso 12 pin, che devono essere sganciati un poâ€™ per volta facendo leva lungo i bordi del telefono.', 'Oukitel U7 Plus.jpg', '2017-06-14', '2017-08-10', '20%', 'mediaworld', '', 'Elettronica', 0),
(45, 'ROG GL553VE', 'ROG GL553 viene fornito con Windows 10 preinstallato e dispone di una CPU di 7 Â° generazione IntelÂ® Coreâ„¢ i7 quad-core, scheda grafica NVIDIAÂ® GeForceÂ® GTX 1050Ti con pieno supporto MicrosoftÂ® DirectXÂ® 12 per darvi prestazioni potenti e una grafica di gioco impeccabile.\r\nROG GL553 viene fornito con Windows 10 pre-installato e vi offre un\'esperienza di gioco veramente coinvolgente grazie alle CPU di settima generazione IntelÂ® Coreâ„¢ i7 e alla scheda grafica dedicata NVIDIAÂ® GeForceÂ® GTX 1050Ti. ROG GL553 Ã¨ realizzato appositamente per il gaming e per la creativitÃ . Provate i giochi e le applicazioni come mai prima d\'ora!\r\nROG GL553 dispone di una tastiera appositamente progettata con retro illuminazione RGB e tasti con corsa di soli 2,5 millimetri per le battute. Sono inoltre evidenziati i tasti WASD in modo da sapere dove le apporre le mani. Inoltre la barra spaziatrice piÃ¹ grande e i tasti freccia isolati, contribuiscono a mantenere a portata di mano tutti i comandi necessari.\r\nASUS Cooling Overboost permette di regolare la velocitÃ  delle ventole, e grazie ad un design termico intelligente permette la massima efficienza di raffreddamento, per dare a ROG GL553 la stabilitÃ  necessaria per le maratone di gioco.', NULL, '2017-06-14', '2017-08-14', '30%', 'unieuro', '', 'Elettronica', 0),
(46, 'ROG Gladius II', 'Armatevi e mirate con il mouse da gioco ottico ROG Gladius II, successore del mitico Gladius originale e successivo passo avanti nell\'evoluzione dei mouse da gioco. Gladius II dispone di un sensore ottico avanzato da 12000 DPI e pulsante di regolazione DPI per la massima accuratezza di mira â€“ i nemici possono anche fuggire, ma non possono nascondersi. E con la tecnologia di illuminazione di ASUS Aura Sync, potrete eclissare la concorrenza.\r\nI giocatori professionisti hanno avuto una grande ruolo nella fase di progettazione di ROG Gladius II. Il risultato Ã¨ un mouse estremamente confortevole, ad alte prestazioni, perfetto per tutti i giocatori e qualsiasi stile di presa. \r\nROG Gladius II Ã¨ progettato per dominare â€“ e attirare gli sguardi grazie alla sua estetica aggressiva e alla tecnologia di illuminazione RGB Aura di ASUS. Con sei effetti di luce personalizzabili pre-impostati e prestazioni incredibili, i Gladius II Ã¨ pronto per la battaglia!', 'ROG Gladius II.jpg', '2017-06-14', '2017-09-14', '10%', 'euronics', '', 'Elettronica', 0),
(47, 'ROG STRIX', 'ROG Strix GeForceÂ® Le schede grafiche GTX 1060 gaming integrano tecnologie esclusive ASUS, compresa la tecnologia DirectCU III con alette di raffreddamento brevettate capaci di migliorare del 30% le prestazioni con insonorizzazione 3 volte superiore e con la tecnologia esclusiva Auto-Extreme per mirorare qualitÃ  e affidabilitÃ . Aura RGB consente la personalizzazione del sistema di gioco e le porte HDMI VR-friendly permettono ai giocatori di godere facilmente di esperienze di realtÃ  virtuale. ROG Strix GeForceÂ® GPU Tweak II con Xsplit Gamecaster, fornisce un intuitivo tweaking delle prestazioni e consente lo streaming istantaneo del vostro gioco.\r\nEsclusiva tecnologia di raffreddamento DirectCU III che dispone di due esclusivi condotti da 10 millimetri a contattodiretto con la GPU capaci di dissipare il 40 % in piÃ¹ di calore e migliorare le prestazioni di raffreddamento del 30 %.', 'ROG STRIX-GTX1060-O6G-GAMING.png', '2017-06-14', '2018-06-12', '20%', 'euronics', '', 'Elettronica', 0),
(48, 'Samsung Galaxy J510', 'La giusta combinazione di design e potenza. Grazie alla nuova cornice in metallo e all\'ampio display superAmoled da 5.2\'\', il tuo nuovo Galaxy J5 2016 ti garantisce la massima ergonomia ed uno stile distintivo.\r\nOgni momento Ã¨ importante. Visualizza immagini incredibilmente luminose e scatta foto in qualunque condizione di luce grazie agli obiettivi con F/1.9. Non lasciarti sfuggire nessun attimo importante, sfruttando l\'Avvio Rapido della fotocamera con un semplice doppio click sul tasto Home.\r\nCattura sempre il lato migliore di te, utilizzando tutte le nuove funzionalitÃ  della fotocamera da 13 MP e 5 MP. Grazie al FlashLED frontale e alle funzioni di ritocco, potrai visualizzare solo le tue pose migliori ed impostrare lo scatto perfetto in pochissimi secondi.', 'Samsung Galaxy J510.jpg', '2017-06-14', '2018-06-14', '20%', 'mediaworld', '', 'Elettronica', 0),
(49, 'ZenFone 3 Laser', 'La vita scorre rapidamente come accade spesso con i momenti piÃ¹ belli. ZenFone 3 Laser Ã¨ in grado di catturare le immagini con una fulminea messa a fuoco in soli 0,03 secondi scattando fotografie sempre impeccabili, alla velocitÃ  della luce. Inoltre, il suo design in pregiato metallo offre uno stile impareggiabile â€“ tutto questo, con ZenFone 3 Laser.\r\nLa nuova tecnologia PixelMaster 3.0 rende ZenFone 3 Laser capace di catturare video ed immagini di qualitÃ  assolutamente elevata, al di sopra di ogni standard. PixelMaster 3.0 integra una fotocamera da 13MP con sensore Sony, un grande obiettivo con apertura f / 2.0 e auto-focus ad esposizione automatica che cattura fotografie a qualsiasi distanza in soli 0,03 secondi. Grazie alla stabilizzazione ottica ed elettronica e al sensore di correzione del colore otterrete risultati di qualitÃ  impeccabile - la rivoluzione PixelMaster 3.0 Ã¨ giunta nelle vostre mani.\r\nLa fotocamera posteriore di ZenFone 3 Laser integra la 2Â° generazione del fulmineo auto-focus laser che consente una messa a fuoco istantanea in soli 0,03 secondi. Lo smartphone emette un raggio laser che misura le distanze con incredibile velocitÃ . Lâ€™auto-focus laser ottimizza gli scatti effettuati a distanza ravvicinata, compensando il movimento creato dalla lente durante lâ€™inquadratura - cosÃ¬ ogni scatto viene catturato piÃ¹ velocemente beneficiando di maggiore nitidezza!', 'ZenFone 3 Laser (ZC551KL).jpg', '2017-06-14', '2017-08-14', '30%', 'unieuro', '', 'Elettronica', 0);

-- --------------------------------------------------------

--
-- Struttura della tabella `utenti`
--

CREATE TABLE `utenti` (
  `Id_user` int(11) NOT NULL,
  `Nome` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `Cognome` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `Genere` varchar(1) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `Eta` tinyint(4) NOT NULL,
  `Email` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `Telefono` decimal(10,0) NOT NULL,
  `User` varchar(50) CHARACTER SET latin7 COLLATE latin7_general_cs NOT NULL,
  `Pass` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `Livello` varchar(10) COLLATE utf8_bin NOT NULL,
  `Coupon_emessi` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--
-- Dump dei dati per la tabella `utenti`
--

INSERT INTO `utenti` (`Id_user`, `Nome`, `Cognome`, `Genere`, `Eta`, `Email`, `Telefono`, `User`, `Pass`, `Livello`, `Coupon_emessi`) VALUES
(6, 'Prof', 'Prof', 'M', 18, 'prof2@gmail.com', '1234567890', 'user', '7Mby', 'user', 105),
(7, 'prof', 'Prof', 'M', 38, 'prof@gmail.com', '1234567896', 'staff', '7Mby', 'staff', 0),
(8, 'Prof', 'Prof', 'M', 11, 'prof3@gmail.com', '1234567898', 'admin', '7Mby', 'admin', 0),
(9, 'Giuseppe', 'Cannata', 'M', 28, 'ghjk@gmail.com', '456', 'giuseppe', '0000', 'user', 1),
(10, 'dd', 'dd', 'F', 35, 'dd@gmail.com', '345', 'xxxx', '0000', 'user', 0);

--
-- Indici per le tabelle scaricate
--

--
-- Indici per le tabelle `aziende`
--
ALTER TABLE `aziende`
  ADD PRIMARY KEY (`Id_azienda`);

--
-- Indici per le tabelle `categoria`
--
ALTER TABLE `categoria`
  ADD PRIMARY KEY (`Id_categoria`);

--
-- Indici per le tabelle `coupon_emessi`
--
ALTER TABLE `coupon_emessi`
  ADD PRIMARY KEY (`Id_coupon`);

--
-- Indici per le tabelle `faq`
--
ALTER TABLE `faq`
  ADD PRIMARY KEY (`Id_faq`);

--
-- Indici per le tabelle `promozione`
--
ALTER TABLE `promozione`
  ADD PRIMARY KEY (`Id_promozione`);

--
-- Indici per le tabelle `utenti`
--
ALTER TABLE `utenti`
  ADD PRIMARY KEY (`Id_user`);

--
-- AUTO_INCREMENT per le tabelle scaricate
--

--
-- AUTO_INCREMENT per la tabella `aziende`
--
ALTER TABLE `aziende`
  MODIFY `Id_azienda` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;
--
-- AUTO_INCREMENT per la tabella `categoria`
--
ALTER TABLE `categoria`
  MODIFY `Id_categoria` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;
--
-- AUTO_INCREMENT per la tabella `coupon_emessi`
--
ALTER TABLE `coupon_emessi`
  MODIFY `Id_coupon` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=126;
--
-- AUTO_INCREMENT per la tabella `faq`
--
ALTER TABLE `faq`
  MODIFY `Id_faq` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=22;
--
-- AUTO_INCREMENT per la tabella `promozione`
--
ALTER TABLE `promozione`
  MODIFY `Id_promozione` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=50;
--
-- AUTO_INCREMENT per la tabella `utenti`
--
ALTER TABLE `utenti`
  MODIFY `Id_user` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
