<?php echo $this->doctype() ?>

<html>
    
    <head>
        <?= $this->headMeta(); ?>
        <title>Coupon</title>
        <link href= "<?= $this->baseUrl('css/Coupon.css');?>" rel="stylesheet" type="text/css" />
    </head>
    
    <body>
        

            <img src="<?= $this->baseUrl('img/coupon.jpg'); ?>">
            <div id="info">
            <?php
            
              echo '<h4>Rilasciato a:  <small>'. $this->authInfo('Nome').'   '. $this->authInfo('Cognome') .'</small></h4>';
              echo '<h4>Nome promozione: <small>'. $this->Nome_promozione .'</small></h4>';
              echo '<h4>Categoria: <small>'. $this->Categoria .'</small></h4>';
              echo '<h4>Offerta: <small>'. $this->Offerta .'</small></h4>';
              echo '<h4>Azienda: <small>'. $this->Azienda .'</small></h4>';   
               echo '<h4>Localizzazione azienda: <small>'. $this->Localizzazione .'</small></h4>';  
              echo '<h4>Valida entro la data: <small>'. $this->Fine_promozione .'</small></h4>';
              echo '<br><br><br><h4>Id coupon: <small>'. $this->Id_coupon .'</small></h4>';
              
            ?>
        </div>
    </body>
</html>

