<h1 class="Titolo">Modifica categoria</h1>
<h3 class="Sottotitolo"> Benvenuto nella sezione inserisci modifica categoria!</h3>
<h3 class="Sottotitolo"> Seleziona la categoria che desideri cambiare;</h3>
<h3 class="Sottotitolo"> Successivamente digita il nuovo nome.</h3>
<br>
<br>

<div>
    <?= $this->modificaCategoriaForm; ?>
</div>
<a href="<?= $this->url(array('controller' => 'admin',
                                    'action' => 'gestionecategorie'), 
                                    'default',true ); ?>"><button class="bottom">Indietro</button></a>

