

<div>
    <h1 class="Titolo">Statistiche CouponLand.it</h1>
    <h3>Monitora l andamento di CouponLand.it in pochi minuti!</h3>
</div>

<div>
   <h4>Coupon emessi: <?php echo $this->N_couponEmessi; ?> </h4>
    <p>
        <label>Scegli la promozione che ti interessa</label>
        
         <select name="promozione" size="1">
         <?php foreach ($this->promTUTTE as $promozioni){
                echo '<option>'. $promozioni->Nome .'</option>'; 
             }
          ?>
         
        </select>
    </p>
</div>




