<?php $this->headScript()
        ->appendFile($this->baseUrl('js/jquery.js', 'text/javascript'))
        ->appendFile($this->baseUrl('js/functions.js', 'text/javascript'))
        ->captureStart(); ?>

$(function(){

	var actionUrlProm='<?= $this->url(array('controller' => 'admin', 'action' => 'segnalacoupon',), 'default');  ?>';
        var actionUrlUser='<?= $this->url(array('controller' => 'admin', 'action' => 'segnalacouponuser',), 'default');  ?>';
	var formNameProm='<?= $this->promselectForm->getName() ?>';
        var formNameUser='<?= $this->userselectForm->getName() ?>';
       
                $('#prom').change(function (event) {
                    $('#numcoupon').empty();
                     $('#azienda').empty();
                   setInfo(actionUrlProm,formNameProm); 
                   
                });
                
                
                
                $('#user').change(function (event) {
                    $('#numcouponuser').empty();
                     
                   setInfoUser(actionUrlUser,formNameUser); 
                   
                });
                
                
                
                
}); 
<?php $this->headScript()->captureEnd() ?>

<div>
    <h1 class="Titolo">Statistiche CouponLand.it</h1>
    <h3>Monitora l andamento di CouponLand.it in pochi minuti!</h3>
</div>

<div>
   <h4>Coupon emessi totali: <?php echo $this->N_couponEmessi; ?> </h4>
    <div>
   
   <?php echo $this->promselectForm ?>
    <h4>Coupon emessi:<h1 id = "numcoupon"></h1> </h4>
    <h4> Azienda: <h1 id = "azienda"></h1> </h4>
    </div>

<div>
    <?php echo $this->userselectForm ?>
    <h4>Coupon emessi:<h1 id = "numcouponuser"></h1> </h4>
</div>
</div>






