<h1 class="Titolo">Modifica azienda</h1>
<h3 class="Sottotitolo"> Benvenuto nella sezione modifica azienda!</h3>
<h3 class="Sottotitolo"> Al termine fai click su fatto.</h3>
<br><br>

<div>
 
    <?= $this->modificaAziendaForm; ?>
    
</div>
<a href="<?= $this->url(array('controller' => 'admin',
                                    'action' => 'listaziende'), 
                                    'default',true ); ?>"><button class="bottom">Torna alla lista</button></a>



