<h1 class="Titolo">Modifica utente</h1>
<h3 class="Sottotitolo"> Benvenuto nella sezione modifica utente!</h3>
<h3 class="Sottotitolo"> Al termine fai click su modifica.</h3>
<br><br>

<div>
 
    <?= $this->modificautenteForm; ?>
    
</div>
<a href="<?= $this->url(array('controller' => 'admin',
                                    'action' => 'listutenti'), 
                                    'default',true ); ?>"><button class="bottom">Torna alla lista</button></a>

